### ISSUE TITLE
Error when using excon adapter with ruby 3

### ISSUE THREAD

**Issue by nickrisaro** [bblimke/webmock#1007]
I have a subclass of `Excon::Connection` defined like this

```Ruby
module MyApp::Clients
  class ExternalAPI < Excon::Connection
    def initialize(
      api_url: MyApp::Config.api_url,
      authorization: nil,
      headers: {},
      request:,
    )
      uri = URI.parse(api_url)
      super(
        host: uri.host,
        path: uri.path,
        port: uri.port,
        scheme: uri.scheme,
        headers: headers,
        instrumentor: MyApp::ExconInstrumentor.new
      )    
    end
end
```

From my code i call it with
```Ruby
MyApp::Clients::ExternalAPI.new(**options).post(path: PATH, expects: 201)
```

I am in the process to migrate the app from Ruby 2.7.6 to Ruby 3.1.2, when I enabled deprecation warnings I started seeing this when running the test suite

```
/Users/srisaro/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/excon_adapter.rb:157: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/srisaro/Projects/my-app/lib/app/clients/external_api.rb:5: warning: The called method `initialize' is defined here
```

If I switch from Ruby 2.7 to Ruby 3 those warnings become errors

```
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: request)
    /Users/srisaro/Projects/my-app/lib/app/clients/external_api.rb:5:in `initialize'
    /Users/srisaro/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/excon_adapter.rb:157:in `new'
    /Users/srisaro/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/excon_adapter.rb:157:in `new'
```

I looked at [the adapter](https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/excon_adapter.rb#L154) and found that it is directly passing the args to `super` and, in Ruby 3, this is incompatible with named arguments.

If I add this redefinition in my test setup all tests pass without warnings/errors (Notice the `**args` on the call to `super`)

```Ruby
Excon::Connection.class_eval do
  def self.new(args = {})
    args.delete(:__construction_args)
    super(**args).tap do |instance|
      instance.data[:__construction_args] = args
    end
  end
end
```

Can this change be added to the Excon Adapter or should I rewrite my code to avoid using named parameters on the initializer?

I believe this is related to [this](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) change on Ruby 3.

**Comment by bblimke** [comment]
@nickrisaro I believe the problem is that you call super with keyword args while if you look at ExconConnection initialize it takes a single argument params, and not keyword args.

You should change your implementation to:

```Ruby
module MyApp::Clients
  class ExternalAPI < Excon::Connection
    def initialize(
      api_url: MyApp::Config.api_url,
      authorization: nil,
      headers: {},
      request:,
    )
      uri = URI.parse(api_url)
      super({
        host: uri.host,
        path: uri.path,
        port: uri.port,
        scheme: uri.scheme,
        headers: headers,
        instrumentor: MyApp::ExconInstrumentor.new
      })    
    end
end
```
