### ISSUE TITLE
Request for documentation re: scope of stubs in rspec

### ISSUE THREAD

**Issue by akotranza** [bblimke/webmock#1008]
Experienced some serious gaslighting trying to do something like

```
before :all do
  stub_request(:get, "https://example.org/.well-known/openid-configuration").to_return(status: 200, body: "", headers: {})
end

it 'does xyz' do
  # do the thing that makes the GET call to the above uri
end
```

And getting
```
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://example.org/.well-known/openid-configuration with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'access-dev.healthcare.elsevier.com', 'User-Agent'=>'Ruby'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "https://example.org/.well-known/openid-configuration").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Host'=>'access-dev.healthcare.elsevier.com',
       	  'User-Agent'=>'Ruby'
           }).
         to_return(status: 200, body: "", headers: {})
```

(Yes same result if copy pasting the exact stub_request into the test)

Because the stub is only good for a single call? Lots of googling and I don't see this documented clearly. Was not how I would expect it to work coming from other (non ruby/rails) mocking frameworks. Expected the scope of the stub to be the same as the testing scope in which it was used. Would likely save others some headache if this is explicitly stated or shown in any of the examples provided. Thanks

**Comment by bblimke** [comment]
Stubs are reset after every example, so before all won't work. Please check https://github.com/bblimke/webmock/blob/master/lib/webmock/rspec.rb

You can skip not include webmock/rspec and create your own setup.
