### ISSUE TITLE
Remove stub with Regex uri

### ISSUE THREAD

**Issue by dmitri-minkin** [bblimke/webmock#1015]
I came across this scenario.

I want to remove a stub if it already exists in the `WebMock::StubRegistry.instance.request_stubs` without having to save the original stub in my code. Just use the original method and uri as a way to identify my stub. 
This works when building request_signature from uri and method and then searching for the request stub with `WebMock::StubRegistry.instance.registered_request?(request_signature)` but it raises an error when uri is Regex.

Below are two test that I added to webmock repo locally:
"should remove stub from registry for String uri" - passes
"should remove stub from registry for Regex uri" - fails

```ruby
# spec/unit/stub_registry_spec.rb
require 'spec_helper'

describe WebMock::StubRegistry do

  before(:each) do
    WebMock::StubRegistry.instance.reset!
  end

  describe "remove_request_stub" do
    it "should remove stub from registry for String uri" do
       uri = "www.example.com"
       
       request_stub = WebMock::RequestStub.new(:get, uri)
       request_signature = WebMock::RequestSignature.new(:get, uri)
  
       WebMock::StubRegistry.instance.register_request_stub(request_stub)

       expect(WebMock::StubRegistry.instance.registered_request?(request_signature)).to eq(request_stub)
    end

    it "should remove stub from registry for Regex uri" do
       uri = /www.example.com/
       
       request_stub = WebMock::RequestStub.new(:get, uri)
       request_signature = WebMock::RequestSignature.new(:get, uri)
  
       WebMock::StubRegistry.instance.register_request_stub(request_stub)

       expect(WebMock::StubRegistry.instance.registered_request?(request_signature)).to eq(request_stub)
    end
  end
```

## Error
The test "should remove stub from registry for Regex uri" fails with:

>NoMethodError:
       undefined method `path' for /www.example.com/:Regexp

               if normalized_uri.path == '/'
                                ^^^^^
     # ./lib/webmock/util/uri.rb:40:in `variations_of_uri_as_strings'
     # ./lib/webmock/request_pattern.rb:171:in `pattern_matches?'
     # ./lib/webmock/request_pattern.rb:139:in `matches?'
     # ./lib/webmock/request_pattern.rb:37:in `matches?'
     # ./lib/webmock/stub_registry.rb:73:in `block in request_stub_for'
     # ./lib/webmock/stub_registry.rb:72:in `each'
     # ./lib/webmock/stub_registry.rb:72:in `detect'
     # ./lib/webmock/stub_registry.rb:72:in `request_stub_for'
     # ./lib/webmock/stub_registry.rb:60:in `registered_request?'
     # ./spec/unit/stub_registry_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

## Workaround

There is a "brute-force" method to reach into `WebMock::StubRegistry.instance.request_stubs` and compare request_stubs by their string representation:

```ruby
def disable(method, uri)
          s = WebMock::RequestStub.new(method, uri).to_s
          stub = WebMock::StubRegistry.instance.request_stubs.find { |registered_stub| registered_stub.to_s == s }
          WebMock::API.remove_request_stub(stub) if stub
end
```

This breaks the encapsulation that WebMock::API provides since we reach into internal implementation in `WebMock::StubRegistry.instance` and also this approach is brittle since we compare request stubs by their string representation.

**Comment by bblimke** [comment]
@dmitri-minkin is there an issue with `remove_request_stub` from WebMock::API or the issue exists because you operate on WebMock internals, `WebMock::StubRegistry.instance.request_stubs`?
