### ISSUE TITLE
Replace `crack` with `nokogiri`?

### ISSUE THREAD

**Issue by andyw8** [bblimke/webmock#1048]
The latest release of [crack](https://rubygems.org/gems/crack) was over 3 years ago, and there are unresolved issues with Ruby 3.3, such as https://github.com/jnunemaker/crack/pull/75.

Would you consider a PR which switches to Nokogiri instead for XML parsing?

**Comment by andyw8** [comment]
Alternatively, the [very small implementation](https://github.com/jnunemaker/crack/blob/master/lib/crack/xml.rb) could just be copied into the WebMock.

**Comment by bblimke** [comment]
@andyw8 thank you for reporting the issue.

@kiskoza thank you for the rapid response and releasing the new version :) 

If `crack` is still being maintained, I don't see any reason to replace it with copied implementation or heavyweight nokogiri.

@kiskoza do ever you plan to do a 1.x release of crack?

**Comment by kiskoza** [comment]
I'm open to release a `v1` if there's a need for it, let's have a discussion on jnunemaker/crack#63
