### ISSUE TITLE
Cannot use the same url twice

### ISSUE THREAD

**Issue by rdptz** [bblimke/webmock#1052]
It seems WM doesn't support stubbing the same url twice in the same spec. How can this be possibile?
If you run the single "its" below, everything is fine, if you run the whole specs the second one always fails with: 

WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST http://localhost/foobar with body 'BAR' with headers {'Connection'=>'close', 'Content-Type'=>'application/xml', 'Host'=>'localhost', 'User-Agent'=>'http.rb/5.1.1'}

```
  it 'returns the foo' do
    stub_request(:post, 'http://localhost/foobar').with(body: 'FOO').to_return(status: 200, body: '')
    expect(1).to eq(1)
  end

  it 'returns the bar' do
    stub_request(:post, 'http://localhost/foobar').with(body: 'BAR').to_return(status: 200, body: '')
    expect(1).to eq(1)
  end
```

thanks,

**Comment by bblimke** [comment]
@rdptz can you please provide the sample code to reproduce the problem? your example doesn't have any code that executes the request. 
Do you have `require 'webmock/rspec'` in your rails_helper.rb?

**Comment by rdptz** [comment]
Hi, that is the sample code. You cannot stub two requests with the same url. The second spec raises: 

WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST http://localhost/foobar with body 'BAR' with headers {'Connection'=>'close', 'Content-Type'=>'application/xml', 'Host'=>'localhost', 'User-Agent'=>'http.rb/5.1.1'}

Yes I have `require 'webmock/rspec'` in my rails_helper.rb

Everything works fine as long as I do not stub 2 requests with the same url.

**Comment by ukolovda** [comment]
I have the same trouble now...

**Comment by ukolovda** [comment]
> I have the same trouble now...

Sorry, it was my mistake. It works for me.

**Comment by bblimke** [comment]
@rdptz In order to address it, I need a sample code to reproduce the issue. Can you please provide it?

**Comment by rdptz** [comment]
Hi, 

it happened just using the two spec of my first message, but now after upgrading a few gems (actually a lot of them), including rails it is not happening anymore. 

Thanks anyway.

**Comment by bblimke** [comment]
Thank you for the feedback! I'm glad it works for you now :)
