### ISSUE TITLE
Unable to create stubs inside a loop

### ISSUE THREAD

**Issue by joshfester** [bblimke/webmock#1064]
In my test I need to hit the same endpoint multiple times with a slightly different request body and response each time. Here's an example:

```
["one", "two", "three", "four"].each do | foo |
  stub_request(: any, "/https:\/\/example.com.*/")
  .with(body: /.*#{foo}.*/o)
  .to_return(
    status: 200,
    body: Rails.root.join("#{foo}.json").read
  )
end
```

Running the test like this will give me this error:

```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled....
registered request stubs:

stub_request(:any, "/https:\/\/example.com.*/").
  with(
    body: /.*one.*/)
stub_request(:any, "/https:\/\/example.com.*/").
  with(
    body: /.*one.*/)
stub_request(:any, "/https:\/\/example.com.*/").
  with(
    body: /.*one.*/)
stub_request(:any, "/https:\/\/example.com.*/").
  with(
    body: /.*one.*/)
```

Only the first element in the array seems to work. If I don't use a loop and just explicitly stub each one, then the tests run fine. Am I doing this wrong?

**Comment by bblimke** [comment]
@joshfester I apologize for the late response.

The issue you observed is not related to WebMock, but rather to how the `o` modifier you added to the regular expression works.

The `o` modifier causes the string interpolation to be evaluated only once, during the first loop iteration.

Here are some references: 
1. https://stackoverflow.com/a/13334823
2. https://roblog.co.uk/2014/03/regex-o-modifier/

Thank you for opening this issue. I've learned something new about Ruby today! :)

**Comment by joshfester** [comment]
Oh wow that was not even on my radar. With regex I tend to copy examples rather than trust myself 😅

Thank you so much! I just removed about 100 lines of code from my test!
