### ISSUE TITLE
webmock not working with ruby > 3 and open-uri

### ISSUE THREAD

**Issue by jagthedrummer** [bblimke/webmock#1072]
I'm working on updating an app from ruby 2.7 to ruby 3.0. I have one test that fails on ruby 3 but that works fine on ruby 2.7.

The class under test looks basically like this:

```ruby
class MyClass
  require 'open-uri'
  
  def self.read_url(url)
    open(url).read
  end
end
```

The test (rspec) looks basically like this:

```ruby
stub_request(:get, "http://www.octolabs.com").
  with(:headers => {'Accept'=>'*/*'}).
  to_return(:status => 200, :body => "test body", :headers => {})

contents = MyClass.read_url("http://www.octolabs.com")

expect(contents).to eq("test body")
```

Under ruby 3 the test fails like this:

```
Failures:

  1) MyClass read_url should go through webmock
     Failure/Error: open(url).read

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - http://www.octolabs.com
```

If I remove the `stub_request` block it fails in the same way and doesn't suggest a request stub.

**Comment by jagthedrummer** [comment]
Oops, it appears I had missed a deprecation warning under 2.7.

It looks like `open-uri` no longer overrides the generic `open` method, and now you have to call `URI.open`.

I updated my class to look like this, and the problem went away:

```ruby
class MyClass
  require 'open-uri'
  
  def self.read_url(url)
    URI.open(url).read
  end
end
```

**Comment by bblimke** [comment]
I'm glad you managed to sort it out :)
