### ISSUE TITLE
Having too many stubs that open files can cause a too many files open error in 0.8.1

### ISSUE THREAD

**Issue by nielsm** [bblimke/webmock#11]
I have several stub_request calls that use the File.new calls for the body as shown in the examples.  Internally WebMock appears to save these request/response signatures to a hash, but the IO objects they point to are left open.  If you have a lot of stub_request in this pattern you receive Errno::EMFILE: Too many open files, while running your tests.   

Ideally this should be better handled internally to WebMock, such that it cleans up after itself, or alternate examples provided on the README.

**Comment by wbotelhos** [comment]
I don't know why, but it started throw on my Capybara's tests.
The spec has no stub, just 'require 'support/webmock'' to prevent external call.

```
# --- Caused by: ---
     # Errno::EMFILE:
     #   Too many open files - socket(2) for "127.0.0.1" port 9516
     #   /Users/wbotelhos/.rvm/gems/ruby-2.7.0@danca/gems/webmock-3.7.6/lib/webmock/http_lib_adapters/net_http.rb:136:in `start_with_connect_without_finish'
```

```
capybara (3.30.0)
selenium-webdriver (3.142.6)
webmock (3.7.6)
```

**Comment by bblimke** [comment]
@wbotelhos has anything changed just before it started happening. have you upgraded WebMock?

**Comment by wbotelhos** [comment]
Hi @bblimke , just updated Ruby to 2.7.0, but I rolled back to 2.6.5 and it worked again.

**Comment by rjhancock** [comment]
I actually just started having this issue myself, also with Capybara tests. Works fine on Ruby 2.6.5. Not on Ruby 2.7.0.

```
capybara (3.32.1)
selenium-webdriver (3.142.7)
webmock (3.8.3)
rails (6.0.2.2)
webdrivers (4.2.0)
```

Which is leading me to believe this might actually be an issue with Capybara/Selenium and not WebMock as I have roughly 5k calls to File.read using WebMock.

**Comment by rjhancock** [comment]
Locking Capybara to 3.31.0 will solve the issue for the time being until it's fixed.

**Comment by KirillKayumov** [comment]
If anyone is experiencing the problem, take a look at the Gotchas section: https://github.com/teamcapybara/capybara#gotchas
