### ISSUE TITLE
display current registered request

### ISSUE THREAD

**Issue by godfat** [bblimke/webmock#110]
I often run into a problem that looking at the failure message and wondering why the program I want to test is not calling the mocked request? Then I need to look into my code and see what's the difference between mocked one and requested one.

It would be very useful if webmock can display the current registered request for me, then it would be very easy to see the difference.

Take `rr` as an example. This is what `rr` would be printing upon unexpected call:

```
On subject #<Object:0x00000100ae1720>, (RR::Errors::DoubleNotFoundError)
unexpected method invocation:
  something("123")
expected invocations:
- something(123)
```

This is the code to create that failure message:

``` ruby

require 'rr'
include RR::Adapters::RRMethods

stub(o = Object.new).something(123)
o.something('123')

RR.verify
```

As you can see, it's very clear why it failed.

Thanks for consideration!

**Comment by ivancortesromero** [comment]
@bblimke What is the method name?

**Comment by bblimke** [comment]
@ivancortesromero can you please explain? This issue was closed 8 years ago :)

**Comment by ivancortesromero** [comment]
@bblimke I understood you added a new method with a possible name `print_stubbed_requests` but I can't find it. Perhaps you added it with a different name? Sorry if I misunderstood.

**Comment by bblimke** [comment]
@ivancortesromero this method was never added. this issue was solved by printing request stubs by default on unmatched request failure.
