### ISSUE TITLE
query parameters are erroneously unescaped

### ISSUE THREAD

**Issue by FND** [bblimke/webmock#226]
minimal test case:

```ruby
require "net/http"
require "cgi"
require "webmock"

WebMock.stub_request(:any, /.*/).
    with { |req| puts "AFTER : #{req.uri.query}"; true }

uri = URI.parse("http://example.org/?q=#{CGI.escape("foo/bar")}")
puts "BEFORE: #{uri.query}"
req = Net::HTTP::Get.new(uri.to_s)
Net::HTTP.new(uri.host, uri.port).request(req)
```

expected:

    BEFORE: q=foo%2Fbar
    AFTER : q=foo%2Fbar

actual:

    BEFORE: q=foo%2Fbar
    AFTER : q=foo/bar

I assume this is *not* intentional?

**Comment by presidentJFK** [comment]
closing this as it looks like it was solved by #308. If it different than that issue, please reopen. Thanks for submitting.
