### ISSUE TITLE
Escaping of URI delimiter characters

### ISSUE THREAD

**Issue by kjbkjb** [bblimke/webmock#240]
After upgrading from v1.8.7 to v1.9.0, our tests that use VCR started failing with the following error:
  ================================================================================
  An HTTP request has been made that VCR does not know how to handle:
    GET http://localhost:3001/xxxxxxx.json?conditions%5Bxxx_id%5D=1

%5B and %5D are [ and ] respectively. They are general delimiter characters according to section 2.2 of this spec: http://www.ietf.org/rfc/rfc3986.txt

I've tried different versions of rails and vcr to verify that the change happened within WebMock.

**Comment by presidentJFK** [comment]
closing this, as it looks like it might be resolved. If you have more information please reopen. Thanks for submitting.
