### ISSUE TITLE
undefined method `map' for #<String:> in VCR

### ISSUE THREAD

**Issue by phillyslick** [bblimke/webmock#262]
When POSTing a file through Capybara, at least through the 'Soundcloud' gem, raises:

undefined method `map' for #<String:0x007fa8e9d8de68>

changing VCR's hook_into: to fakeweb corrects the error.

Sorry if this should be on VCR's repo instead.

**Comment by presidentJFK** [comment]
Thank you for submitting, however I am closing this because of the time elapsed. If it still an issue, please feel free to open a new issue.
