### ISSUE TITLE
hash_including for Headers

### ISSUE THREAD

**Issue by leifg** [bblimke/webmock#276]
I would really like to use the hash_including matcher on HTTP Headers:

```
stub_request(:post, 'https://test.host').
      with(
        body: expected_body
        headers: hash_including(expected_headers))
```

However I am getting this error:

```
     Failure/Error: stub_request(:post, 'https://test.host').
 NoMethodError:
   undefined method `map' for #<RSpec::Mocks::ArgumentMatchers::HashIncludingMatcher:0x007fc81488e530>
```

I suppose it is raised [on this line](https://github.com/bblimke/webmock/blob/master/lib/webmock/util/headers.rb#L9)

**Comment by klaut** [comment]
weirdly, I am having the same problem as the OP :/
When I omit hash_including Webmocks complains that the headers were not as expected.

**Comment by klaut** [comment]
Nevermind. It was user error :) ... I had a typo in my headers. Confirming that it works alright without using ```hash_including```

**Comment by tanduong** [comment]
For anyone that landed here: https://stackoverflow.com/a/49360133/2724342

Web mock header and params need to be an exact match. Most mismatched is from symbol/string keys.

**Comment by jdalt** [comment]
I understand that header matching only occurs on the subset of headers passed into the `with(headers: ...subset...)` method and this matches *most* of the `hash_including` functionality. It seems that `hash_including` can also match on keys being present (without values being specified, ie `hash_including(:key1, :key2)`). Is there a way to do that in a `with(headers: KEYS_THAT_MOST_APPEAR)` statement?

**Comment by guillaume-tgl** [comment]
And how about `hash_excluding`? I'd like to test that my headers didn't not include any Authorization key.

**Comment by jdalt** [comment]
I think my use case is the inverse of that - verify that headers include an Authorization key but I don't care what it is specifically (in fact I might not even be able to know a priori).

**Comment by guillaume-tgl** [comment]
@jdalt I wasn't really offering a solution to your problem but more adding another use case where it would help to be able to use matchers
