### ISSUE TITLE
[1.13.0] WebMock.disable_net_connect! does not seem to work in rspec 2.13

### ISSUE THREAD

**Issue by ayqazi** [bblimke/webmock#293]
Hello,

I'm using webmock-1.13.0 and rspec-2.13 .

WebMock.disable_net_connect! does not seem to work within specs.  Inside a spec, I do the following:

``` ruby
WebMock.disable_net_connect!
puts WebMock.net_connect_allowed?.inspect

stub_request(:get, 'http://fake.url/abc').to_return(body: 'abcd')
Net::HTTP.get(URI.parse('http://fake.url/abc')).should == 'abcd'
Net::HTTP.get(URI.parse('http://fake.url/def')).should == 'xyz' # PROBLEM LINE
```

Firstly, the puts should say "false", but says "true".

Secondly, on the line marked PROBLEM LINE, I should get a WebMock error saying connections are disabled and instructions on how to set up a stub.  However, instead I get SocketError: getaddrinfo: Name or service not known, meaning it's trying to actually look up the hostname.

Note that when run outside of a spec, it all works fine.  It's somehow the interaction with RSpec that's messing things up for me.

Help?

Thanks

**Comment by alexandru-calinoiu** [comment]
I had the same issue, I ended up with not such a drastic work around, simply disable vcr:

```ruby
    around :each do |example|
      VCR.turned_off { example.run }
    end
```
