### ISSUE TITLE
Defining request stubs in an external config file.

### ISSUE THREAD

**Issue by nicohvi** [bblimke/webmock#338]
I'm wondering if this is possible in the current version of `webmock`:

````
# spec/helpers/api_helper.rb
require 'webmock'

module APIHelper
  include WebMock::API 

  stub_request(:get, api_path).to_return(status: 200)
end
`````

And then including this config only for certain specs (for rspec)
````
# spec_helper.rb

config.include APIHelper, :type => :controller
`````

Without having to explicitly call `stub_request` in  a `before :each` in the actual test suite?

For illustrative purposes, this is how I solve this problem currently (feels hacky):

````
# spec/helpers/api_helper.rb

require 'webmock'
require_relative '../spec_helper'

include WebMock::API

RSpec.configure do |config|
  config.before(:each) do
    stub_request(:get, api_path).to_return(status:200)
  end
end
````

As you can see, I haven't even wrapped the code in a module because then I got an error message saying that `stub_request` was not available.

Thanks :-)

**Comment by presidentJFK** [comment]
Thanks for submitting, however I am going to close this because of the time elapsed. If it still something you'd like to see in webmock, please feel free to open a new issue, or pull request.
