### ISSUE TITLE
When POSTing a hash with Typhoeus, the webmock request body is not a hash

### ISSUE THREAD

**Issue by myronmarston** [bblimke/webmock#339]
I have a VCR user that's having this problem:

https://github.com/vcr/vcr/issues/261#issuecomment-29312211

VCR can't deal with non-string request bodies.  It doesn't know how to encode it.  Typhoeus now has a `Typhoeus::Request#encoded_body` method that will give you the body as a raw string.  I think WebMock should use that.

On a side note, it might be good for webmock to verify that the request body is a string, and print a warning or raise an error if it's not a string, since WebMock's API specifies that it's request object has body as a string.

**Comment by presidentJFK** [comment]
closing this as the information is all in #463.
