### ISSUE TITLE
Excon version warning

### ISSUE THREAD

**Issue by daniel** [bblimke/webmock#347]
I get the warning "You are using Excon 0.25.3. WebMock supports version >= 0.27.5.".

In the gemspec the version specified is ">= 0.22.0", but in excon_adapter.rb you check for '0.27.5'.

**Comment by rafaelcgo** [comment]
I still have this issue...

webmock (1.21.0)
excon (0.45.3, 0.13.4)

How to make webmock use excon 0.45.3 and not 0.13.4?

**Comment by bblimke** [comment]
@rafaelcgo what issue exactly do you have?

WebMock will use whatever version of excon you have loaded. Just load 0.45.3

**Comment by ixti** [comment]
@rafaelcgo I suggest either delete `0.13.4` or use [bundler](http://bundler.io/).

**Comment by rafaelcgo** [comment]
I'm using bundler. I have a Rails app.
The problem is that a have an old version of fog (1.3.1) and it is requiring excon 0.13.4.

The only way is to update fog to a version that requires excon '0.27.5' or higher?

**Comment by ixti** [comment]
@rafaelcgo unfortunately yes. You can't have two different versions of same gem loaded at the same time.

**Comment by rafaelcgo** [comment]
@ixti Got it! Thanks

**Comment by bblimke** [comment]
@ixti thank you for clarifying that :)
