### ISSUE TITLE
NoMethodError: undefined method `closed?' for nil:NilClass

### ISSUE THREAD

**Issue by ajbeach2** [bblimke/webmock#374]
I am working on a rails application that uses the aws sdk.  Through trial and error, I was able to get the stubbing of the http requests working with the aws sdk, however, it was both my development and testing environments, I only want the stubbing in the test environment.  I can't figure how why I am getting this error.  The following is the stack trace, my test_helper.rb, and a snippet from my gem file.  I am using minitest. 

This happens when I ran a test for my Image model, that makes an aws sdk http request to get the meta-data about the image in aws, which is then saved in the Image model inside the rails application.

```
NoMethodError: undefined method `closed?' for nil:NilClass
    ~/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/net/http.rb:1336:in `begin_transport'
    ~/.rvm/gems/ruby-1.9.3-p484/gems/right_http_connection-1.4.0/lib/base/net_fix.rb:159:in `request'
    ~/.rvm/gems/ruby-1.9.3-p484/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/http/connection_pool.rb:330:in `request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/http/net_http_handler.rb:61:in `block in handle'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/http/connection_pool.rb:129:in `session_for'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/http/net_http_handler.rb:55:in `handle'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:252:in `block in make_sync_request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:281:in `retry_server_errors'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:248:in `make_sync_request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:510:in `block (2 levels) in client_request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:390:in `log_client_request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:476:in `block in client_request'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:372:in `return_or_raise'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/core/client.rb:475:in `client_request'
   (eval):3:in `describe_images'
    ~/.rvm/gems/ruby-1.9.3-p484/bundler/gems/aws-sdk-ruby-039bcb009417/lib/aws/ec2/image.rb:220:in `exists?'
    ~/Workspace/myapp/app/models/image.rb:65:in `update_resource'
    ~/Workspace/myapp/test/models/image_test.rb:12:in `block in <class:ImageTest>'
```

This is my test_helper.rb

``` ruby
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
require "rails/test_help"
require 'minitest/rails'

require 'webmock/minitest'
include WebMock

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.(yml|csv) for all tests in alphabetical order.
  fixtures :all
end
```

Gemfile

``` ruby
group :test do
  gem 'minitest-colorize'
  gem 'webmock'
end
```

**Comment by avdmatamoros** [comment]
It seems I'm running into this issue also.

    NoMethodError:
       undefined method `closed?' for nil:NilClass
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/right_http_connection-1.5.0/lib/base/net_fix.rb:159:in `request'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb:38:in `step'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/right_http_connection-1.5.0/lib/base/net_fix.rb:149:in `block in request'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/right_http_connection-1.5.0/lib/base/net_fix.rb:147:in `request'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/mini_profiler/profiling_methods.rb:38:in `step'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/rack-mini-profiler-0.9.3/lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activeresource-4.0.0/lib/active_resource/connection.rb:121:in `block in request'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activeresource-4.0.0/lib/active_resource/connection.rb:118:in `request'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activeresource-4.0.0/lib/active_resource/connection.rb:106:in `block in post'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activeresource-4.0.0/lib/active_resource/connection.rb:216:in `with_auth'
     # /usr/local/rvm/gems/ruby-2.2.1@activerain/gems/activeresource-4.0.0/lib/active_resource/connection.rb:106:in `post'

**Comment by argent-smith** [comment]
@bblimke I just ran into the same issue when turned on webpacker installed. Can I help working on the issue?

**Comment by bblimke** [comment]
Could you please provide the backtrace and version of Ruby?

**Comment by argent-smith** [comment]
Backtrace:
```
2018-08-20 19:35:53 +0000: Rack app error handling request { GET /packs/application-c9c061c49eea9cfc93a05aeac4f29046.css }
#<NoMethodError: undefined method `closed?' for nil:NilClass>
/usr/local/lib/ruby/2.4.0/net/http.rb:1484:in `begin_transport'
/usr/local/bundle/gems/rack-proxy-0.6.4/lib/net_http_hacked.rb:50:in `begin_request_hacked'
/usr/local/bundle/gems/rack-proxy-0.6.4/lib/rack/http_streaming_response.rb:60:in `response'
/usr/local/bundle/gems/rack-proxy-0.6.4/lib/rack/http_streaming_response.rb:29:in `headers'
/usr/local/bundle/gems/rack-proxy-0.6.4/lib/rack/proxy.rb:120:in `perform_request'
/usr/local/bundle/gems/webpacker-3.5.5/lib/webpacker/dev_server_proxy.rb:20:in `perform_request'
/usr/local/bundle/gems/rack-proxy-0.6.4/lib/rack/proxy.rb:57:in `call'
/usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/usr/local/bundle/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Ruby version:
```
root@908e2ba67acd:/usr/src/app# ruby --version
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
```

**Comment by bblimke** [comment]
It's probably conflict with `net_http_hacked.rb` :)

**Comment by bblimke** [comment]
@argent-smith is there webmock anwhere on the stack?

**Comment by argent-smith** [comment]
True :D I'll try to see what's there

**Comment by argent-smith** [comment]
@bblimke no. But if I remove it from `group: :development` or comment it out from the bundle everything works.

**Comment by bblimke** [comment]
Does it happen only during some rake task? If yes, then you could do WebMock.disable! before and then WebMock.enable! after.

**Comment by argent-smith** [comment]
No. It happens when I run `rails s`. I need it in development (legacy customer's API needs to be mocked).

**Comment by bblimke** [comment]
You could also try to change the order of loading these gems and see if anything changes if WebMock is loaded before rack proxy or after rack-proxy.

**Comment by argent-smith** [comment]
Rack-proxy is used by webpacker. Changing the order of webpacker/webmock in Gemfile doesn't help.

**Comment by bblimke** [comment]
Do you use webmock to handle requests made by Net::HTTP or some other client?

**Comment by argent-smith** [comment]
Net::HTTP only afaik.

**Comment by Strayer** [comment]
I'm experiencing the same issue. We are using rack-reverse-proxy to pass asset requests to webpack-dev-server in the test environment – internally this seems to be more or less the same, as it also uses rack-proxy. Is there any way to work around this? I'd love to include webmock in our project, but I can't find a way to integrate it with our reverse-proxy setup.
