### ISSUE TITLE
Webmock interfering with before(:suite || :each) in RSpec.configuration?

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [bblimke/webmock#378]
Ruby 2.1.0
Rails 4.0.3
rspec-rails 2.14.1

My current issue here: http://stackoverflow.com/questions/22585469/rspec-before-suite-not-being-run

I'm trying to stub requests for a given domain on all tests, but the code in the before(:suite) or before(:each) block is never executed when the Webmock gem is bundled. It doesn't even matter whether or not spec_helper.rb contains `require 'webmock/rspec'` and `WebMock.disable_net_connect!(allow_localhost: true)`.

rspec_helper.rb snippet:

``` ruby
RSpec.configure do |config|
    config.before(:each) do
        raise "This should be raised as an error, but it isn't when Webmock is bundled"
        # This is normally where I'd put stub_request but since this block isn't called...
    end
end
```

Also of note, the error is being raised when the geocoder gem tries to do an API lookup to maps.googleapis.com upon the creation of a model via FactoryGirl create() within one of the tests.

**Comment by gthorsen** [comment]
I know this post is old, but I noticed that if you place webmock gem before travis in your test gem group it causes webmock to throw a WebMock::NetConnectNotAllowedError when you do a 'bundle exec rake'.  Placing webmock at the end of the gem list in the test gem group fixed the problem.
