### ISSUE TITLE
Webmock & RSpec 3 deprecations

### ISSUE THREAD

**Issue by tobascodagama** [bblimke/webmock#396]
Just migrated one of my projects to RSpec 3, and I'm getting the following deprecation:

```
WebMock::RequestPatternMatcher implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
```

Didn't cause any failures, so I'd say a fix is low priority, but it should probably be addressed eventually. Happens when using `expect(stubbed_request).to have_been_requested`.

**Comment by abepetrillo** [comment]
I'm getting this using rspec-expectations 3.5.x

**Comment by wksmall** [comment]
I am also seeing this in rspec-expectations 3.5.x

**Comment by bblimke** [comment]
can you please provide a sample code to reproduce that?

**Comment by miha-plesko** [comment]
I'm getting this warning using rspec 3.6.0 and webmock 1.13.0. Sample code:
```ruby
expect(request).to have_been_requested
```
I'd appreciate this being fixed!
