### ISSUE TITLE
WebMock::Response IOError: closed stream

### ISSUE THREAD

**Issue by zzak** [bblimke/webmock#417]
I get the following failure on Ruby 2.0.0:

```
4) HTTPClient when using async requests with WebMock when request stub declares that request should return a response when response was declared as lambda evaluating to a strin
g with a raw response should return response from evaluated file
     Failure/Error: Unable to find matching line from backtrace
     IOError:
       closed stream
     # ./lib/webmock/response.rb:114:in `read'
     # ./lib/webmock/response.rb:114:in `read_raw_response'
     # ./lib/webmock/response.rb:23:in `initialize'
     # ./lib/webmock/response.rb:143:in `new'
     # ./lib/webmock/response.rb:143:in `evaluate'
     # ./lib/webmock/stub_registry.rb:63:in `evaluate_response_for_request'
     # ./lib/webmock/stub_registry.rb:51:in `response_for_request'
     # ./lib/webmock/http_lib_adapters/httpclient_adapter.rb:177:in `block in webmock_responses'
     # ./lib/webmock/http_lib_adapters/httpclient_adapter.rb:47:in `yield'
     # ./lib/webmock/http_lib_adapters/httpclient_adapter.rb:47:in `do_get'
     # ./lib/webmock/http_lib_adapters/httpclient_adapter.rb:39:in `do_get_stream'
```

You can see it on travis here: https://travis-ci.org/bblimke/webmock/jobs/36506755#L121-L134

**Comment by ReyLitch** [comment]
I have the same error in some tests but it doesn't happend randomly. It Always happens with the same stub_request.

    valid_fake_create_response = File.new "#{ Rails.root }/spec/samples/create_response.json"
    stub_request( :post, url ).to_return( valid_fake_response )

And the response file content is the following:

    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    p3p: CP="NON CUR OTPi OUR NOR UNI"
    Cache-Control: private, max-age=0, no-cache
    Date: Fri, 06 Mar 2015 13:17:27 GMT
    Content-Length: 91
    Connection: keep-alive
    Set-Cookie: n=0000001810324; Path=/site_manager
    Set-Cookie: locale=es; Path=/; Expires=Mon, 06 Apr 2015 13:17:26 GMT
    Set-Cookie: session_id=0d6b137b928b75a35814dc761c7375d9431a5966; Path=/; Expires=Sun, 10 Jan 2016 13:17:26 GMT
    Set-Cookie: moonshine.sid=s%3A28ec2e9f-aa91-4d92-9f0d-0a9d5b64253d.JI9wxSY9xrupvoOW1n5OiSFJqMUdkU7aEfguSObsgLk; Path=/
    Set-Cookie: FFAFNFT=!Ot59Uc/FZ06zlglJr3EvYCj6Rfed/cNjgVPPhqMrw51MrSJ3ov59zcdWVpgZI43bh76U7dBJjw==;expires=Fri, 06-Mar-2015 17:17:27 GMT;path=/;

    {"filename":"/2015/03/54f9a8e6a81d01425298df0e_thumb.jpg","_id":"54f9a8e6a81d01425298df0e"}

**Comment by bblimke** [comment]
Thank you for the feedback @ReyLitch 

Are you able to narrow down what caused the error to one of these headers or perhaps body?

**Comment by ReyLitch** [comment]
Finally, I have found the problem. I was using the response of a GET request for stubbing a POST request by mistake. Sorry and thanks for your help.

**Comment by presidentJFK** [comment]
closing this. Thanks for submitting!
