### ISSUE TITLE
Partial query matching with hash_including, not working

### ISSUE THREAD

**Issue by afazio** [bblimke/webmock#426]
Partial query matching with hash_including is not working in 1.20.0

[Here is a gist](https://gist.github.com/afazio/8562ba6ef8146d7b217b) showing the logs from webmock.  A `WebMock::NetConnectNotAllowedError` exception is raised for a URL that I have stubbed using partial query matching.  The same log shows `registered request stubs`, and my stub for that URL is clearly listed.  A quick glimpse shows that the registered stub matches perfectly the web request URL that throws an error.

Note that if I do not use partial matching using hash_including, but instead match against the full URL, the code works.

**Comment by presidentJFK** [comment]
closing this as its the same issue as #451
