### ISSUE TITLE
Mocking when Ruby calls server-side JavaScript which calls a web service

### ISSUE THREAD

**Issue by snoblenet** [bblimke/webmock#437]
I use the PhantomJS gem in my app.

https://github.com/colszowka/phantomjs-gem

I use it to execute PhantomJS code from Ruby, like this:

```
Phantomjs.run("./app/assets/javascripts/trigger.js", file.path).html_safe
```

This triggers a PhantomJS script that interacts with Google' Google Charts API.

Likewise, I use the Screencap gem.

https://github.com/maxwell/screencap

This triggers a PhantomJS script that grabs an entire webpage for screenshotting.

Webmock currently intercepts my "pure Ruby" calls to external web services, but not these "Ruby via JavaScript" calls.

Is there any way to intercept these external calls within Rspec using webmock?

I had a look at puffing-billy, but the docs give the impression that this is solely for use within headless browsers driven by Capybara or similar.

https://github.com/oesmith/puffing-billy

**Comment by presidentJFK** [comment]
closing this, since it is outside the project's scope. Thanks for submitting.
