### ISSUE TITLE
Webbock doesn't work with Windows Azure Blob storage

### ISSUE THREAD

**Issue by EugZol** [bblimke/webmock#440]
Trying to use VCR + webmock with Windows Azure Blob storage Ruby library (https://github.com/johnnyhalife/waz-storage).

I'm getting the following error:
    .rvm/gems/ruby-2.1.1/gems/waz-storage-1.3.6/lib/waz-storage.rb:27:in `<module:Net>': superclass mismatch for class HTTP (TypeError)

Related code from waz-storage gem:

    module Net
      class HTTP < Protocol
        class Merge < HTTPRequest
          METHOD = 'MERGE'
          REQUEST_HAS_BODY = true
          RESPONSE_HAS_BODY = false
        end
      end
    end

    https://github.com/johnnyhalife/waz-storage/blob/master/lib/waz-storage.rb

Any thoughts on how could I try to fix it?

**Comment by presidentJFK** [comment]
Closing this for lack of information and time elapsed. If you have more info, please reopen.
Thanks for submitting the issue!
