### ISSUE TITLE
Boolean values need to be passed as strings to query ("true" instead of true)

### ISSUE THREAD

**Issue by riggy** [bblimke/webmock#451]
Hey,

I find it strange since you can actually pass a hash of options as a stubbed query, like
   
    stub_request(:post, "http://something.com").with(query: {some_boolean_option: true})

but the actual url is registered like this:

    http://something.com?some_boolean_option # yeah, nothing here...

It seems that boolean values are not converted to string when constructing stubbed url. Passing value as string works well. It's pretty annoying as it breaks consistency of my tests. Is it intentional or is it just an error or whatever?

**Comment by bblimke** [comment]
It looks like a bug. All query values should be strings, since there is no other way to transfer these via query string.

**Comment by presidentJFK** [comment]
closing now that #513 has been merged in.
