### ISSUE TITLE
Error: no implicit conversion of Hash into String

### ISSUE THREAD

**Issue by rsund55** [bblimke/webmock#452]
When attempting to match a request body against a hash I receive the error "TypeError: no implicit conversion of Hash into String". According to the Readme the body can be JSON which is what I'm using. The stack trace states the error is occurring in "webmock-1.20.4/lib/webmock/util/json.rb:24:in `initialize'". If I remove the *with(:body)* matcher everything works fine.

My request looks like the following:
```ruby
    WebMock.stub_request(:post, "http://localhost:4000/class/create").
      with(:body => {"amount" => 0.0, "value2" => "A", "value3" => "V"}).
      to_return(status: 500,
        body: "",
        headers: {})
```

**Comment by bblimke** [comment]
Would you mind sharing the stacktrace? At least WebMock part.

Does it work if you do `JSON.generate({"amount" => 0.0, "value2" => "A", "value3" => "V"})`?

**Comment by bblimke** [comment]
btw. what is the content type set on that request?

**Comment by hotgazpacho** [comment]
Running into this myself, trying to do partial hash matching using `a_hash_including`. 
Content type is `application/x-www-form-urlencoded`

**Comment by hotgazpacho** [comment]
For what it is worth, this is how I'm making the HTTP request:
```ruby
payload = payload(channel, data)
http = Net::HTTP.new(endpoint.hostname, endpoint.port)
http.use_ssl = endpoint.scheme == 'https'
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
http.ssl_version = :TLSv1_2
request = Net::HTTP::Post.new(endpoint)
request.set_form_data(message: JSON.dump(payload))
http.request(request)
```

And the spec:
```ruby
request = stub_request(:post, "https://example.com/path").
            with(
              body: a_hash_including(
                      message: {
                        data: {
                                 title: document.title,
                               }
                      }))
```

**Comment by hotgazpacho** [comment]
Ugh. I just realized that I'm calling `JSON.dump` to encode the data in the `message` parameter.

**Comment by presidentJFK** [comment]
I'm going to close this for now, as it looks like we don't have enough info. If you can recreate the bug in a test or have a stacktrace of the problem, please reopen and we can try and figure out what's going on. Thanks for submitting the issue!
