### ISSUE TITLE
NoMethodError: undefined method `World' for main:Object

### ISSUE THREAD

**Issue by sachin-kumar-rathore** [bblimke/webmock#453]
[17] pry(#<RSpec::Core::ExampleGroup::Nested_1::Nested_1>)> require 'webmock/cucumber'
NoMethodError: undefined method `World' for main:Object
from /home/rails/.rvm/gems/ruby-1.9.3-p125-falcon@gemset/gems/webmock-1.17.4/lib/webmock/cucumber.rb:4:in `<top (required)>'

**Comment by bblimke** [comment]
Why would you require cucumber inside RSpec?

Cucumber is not loaded so `World` is not defined.

**Comment by sachin-kumar-rathore** [comment]
we havn't loaded cucmber in gem file, Please close this issue
