### ISSUE TITLE
Invalid scheme format. (Addressable::URI::InvalidURIError)

### ISSUE THREAD

**Issue by beanieboi** [bblimke/webmock#489]
Hi,

i get the Invalid scheme format. (Addressable::URI::InvalidURIError) error when i use templates with Webmock. i traced the error down this this line https://github.com/bblimke/webmock/blob/master/lib/webmock/request_pattern.rb#L136

`uri = "http://127.0.0.1:50153/__identify__"`
and where 
`WebMock::Util::URI.variations_of_uri_as_strings(uri)`
creates the following array:
`["http://127.0.0.1:50160/__identify__", "127.0.0.1:50160/__identify__"]`
passing that to `any?` where the `@pattern.match(u)` throws the exception when comparing with the second element from the hash.

i looked up `WebMock::Util::URI.variations_of_uri_as_strings(uri)` and it creates them on purpose.

```
if normalized_uri.scheme == "http"
  uris = uris_with_scheme_and_without(uris)
end
```

so i assume that array of URI's is correct. what other thing could go wrong here?
can you point me at something to debug?

_UPDATE_

thats not the URI i want to template.

```
bitbucket_uri = Addressable::Template.new("https://bitbucket.org/api/1.0/repositories/codeship/{bitbucket_repo_name}/services")
  WebMock.stub_request(:get, bitbucket_uri).
    to_return(status: 200)
```

i guess thats coming from some other tool in our cucumber suite. but if i remove any template from Webmock, the error is gone.
thanks
ben

**Comment by ngauthier** [comment]
I believe this is an issue with Addressable's parser:

```
[1] pry(main)> Addressable::URI.parse("http://127.0.0.1/")
=> #<Addressable::URI:0x3fc2960f6df4 URI:http://127.0.0.1/>
[2] pry(main)> Addressable::URI.parse("127.0.0.1/")
=> #<Addressable::URI:0x3fc2960c93f4 URI:127.0.0.1/>
[3] pry(main)> Addressable::URI.parse("127.0.0.1/_")
=> #<Addressable::URI:0x3fc296098ce0 URI:127.0.0.1/_>
[4] pry(main)> Addressable::URI.parse("127.0.0.1/__")
=> #<Addressable::URI:0x3fc29606f8a4 URI:127.0.0.1/__>
[5] pry(main)> Addressable::URI.parse("127.0.0.1:123")
Addressable::URI::InvalidURIError: Invalid scheme format.
[6] pry(main)> Addressable::URI.parse("foo:123")
=> #<Addressable::URI:0x3fc2960199cc URI:foo:123>
```

I think the addressable parser is to fault here. The numeric ip and port without a scheme causes it to think the ip is the scheme. Webmock, by stripping the scheme from the uri is exacerbating the issue, but I think the root is Addressable::URI's regex.

**Comment by idanelor** [comment]
Is there any workaround on this issue?

**Comment by garytaylor** [comment]
Has the addressable issue been raised anywhere ?  I am having same issue and struggling to even find a workaround without monkey patching :-(

**Comment by bblimke** [comment]
@garytaylor what version of addressable do you user? does this work for you in any version of addressable?

**Comment by skinnyfit** [comment]
Same thing here, even with the third-party Addressable gem. Interestingly, this issue seems to only appear when I pass an `Addressable::Template` to `stub_request`... using a string or regex for the URI argument seemed fine.

Anyway, afraid I don't have time right now to work on a Pull Request, but if anyone else is desperate, this monkey patch got me out of a corner:

```ruby
module WebMock
  class RequestPattern
    alias_method :_matches?, :matches?

    def matches?(request_signature)
      return if request_signature.uri.host == '127.0.0.1' && request_signature.uri.path == '/__identify__'
      _matches?(request_signature)
    end
  end
end
```

**Comment by starrychloe** [comment]
@skinnyfit  That didn't work.

```
     Failure/Error: _matches?(request_signature)

     Addressable::URI::InvalidURIError:
       Invalid scheme format: 127.0.0.1
     # ./spec/config/webmock.rb:41:in `matches?'
```

**Comment by asavageiv** [comment]
@bblimke I think this should be re-opened until #844 is merged or this is otherwise resolved. As of today this is still broken. WebMock is incorrectly passing things like `127.0.0.1:1234` to Addressable as valid URIs which they are not because they are missing a valid scheme.

**Comment by bblimke** [comment]
@asavageiv hopefully this will be resolved by https://github.com/bblimke/webmock/pull/890
