### ISSUE TITLE
specs out of date

### ISSUE THREAD

**Issue by tmertens** [bblimke/webmock#494]
The readme for webmock states to use the command `bundle exec rspec spec/**/*_spec.rb` (with rvm across ruby versions).  However, this pattern omits a large swath of tests.  Using the aforementioned pattern, only 241 specs run.

If you instead run `bundle exec rake`, 3941 examples are executed, with 40 failures reported (ruby 2.1.5).  Furthermore, this is the command used on travis, at least for newer ver

There are a couple issues here:

1. The readme is either out of date, or the tests are.  The readme should be updated and tests should be updated to either pass or if the tests are no longer valid, they should be deleted.  It appears that the assertions are valid for older versions of ruby, but not newer ones (see below).  It seems in the interest of forward progress to make these tests work on newer / supported versions of ruby, or fix them to pass on all versions.

2. The ruby versions listed in the documentation do not align with the versions on travis, and omits all of the newer versions (2.x).  All of the versions listed on the readme are no longer maintained and some/most do not install out of the box (on OS X 10.10) using rvm without additional work.  Once installed, there are additional challenges in getting webmock gem dependencies installed on older versions of ruby.  For ease of development, I would personally recommend dropping the requirement for running tests locally on old ruby versions and stick to 2.x+ (or 1.9.3 at the earliest), and let travis pick up the slack for older versions if there are plans to actually continue support for long abandoned versions of ruby.

Is there any direction on the above two issues? I may be able to work up a PR to address some of the test/documentation issues, but want to get direction from the maintainers first to avoid wasted effort if this does not align with your roadmap.

**Comment by bblimke** [comment]
@tmertens thank you for opening this issue.

All specs should be executed, therefore `bundle exec rake` is the correct command to run it.

I have been keeping support for Ruby 1.8.7 since it didn't require any additional effort and WebMock was easily able to support these.

I'm keen to keep support for Ruby 1.8.7, unless it makes development a pain.
Could you please provide more info on problems when installing Ruby 1.9.2 and 1.8.7?
I'm using Rbenv and had no issues with it.

**Comment by presidentJFK** [comment]
On the topic of dropping support for 1.8.7. Addressable has dropped support of 1.8.x as of 2.3.8
https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md

we have an open >= 2.3.6 in the gemspec so 2.3.8 is what is installed for 1.8.7 running on travis (and passing now!)

We might want to lock down the version, which I'm trying out on different ruby versions now.
Just something I noticed as I'm looking into all these failures.

**Comment by presidentJFK** [comment]
#509 relevant PR to fix the spec failures.

**Comment by presidentJFK** [comment]
Thanks for taking time to give such detailed notes, 
I have now merged #509 and specs are now passing on CI, so I am going to close this issue for now.

 We can start a separate discussion for figuring out what ruby versions we should support in the future, and getting the CI updated to run Rubinus and Ruby 1.9.1 which are the two versions listed in the readme not running on Travis currently
