### ISSUE TITLE
Webmock breaks peer_cert method

### ISSUE THREAD

**Issue by pyrat** [bblimke/webmock#50]
Hi, 

The inclusion of the webmock gem breaks the peer_cert method for getting x509 Certificates. The following code does not work when webmock has been added to the Gemfile.

<pre>
http.start do |conn|
  cert = OpenSSL::X509::Certificate.new conn.peer_cert
  @cert = cert
 end
</pre>

Sorry I havent had time to look through and propose a solution. Any suggestions would be welcome.

Am using Ruby 1.9.2

Cheers,
Alastair

**Comment by mcr** [comment]
It's not obvious to me how to find the Net::HTTP handler which will be used so that I can mock the peer_cert method.  How did you handle that?

**Comment by mcr** [comment]
This is what I've done in my rspec code.  I can set StubIo.instance.peer_cert = to something so that my code can see a mocked TLS Server Certificate.

    class StubIo
      include Singleton
      attr_accessor :peer_cert
    end

    # monkey patch this so that a peer_cert can be returned
    class StubSocket
      def io
        StubIo.instance
      end
    end

**Comment by pboling** [comment]
```
class StubSocket #:nodoc:
  class StubIO
    # Override the standard peer_cert method, which return nil, so that it returns a Cert stub
    def peer_cert
      StubCert.new(extensions: [], subject: {"CN" => "openid.example.org"})
    end
  end

  class StubCert
    attr_accessor :options

    def initialize(**options)
      @options = options
    end

    private def method_missing(symbol, *_args)
      options[symbol]
    end
  end
end
```

**Comment by bblimke** [comment]
@pboling thank you for sharing your solution. As I understand, your code returns a StubCert that is specific to your usecase. Do you have any ideas on how to make it generic to make it work for everyone?

**Comment by pboling** [comment]
The solution above does work for my use case, and it would work for the other use cases described by others in this thread.  I think it solves most, if not all, because the method missing spits out what is passed in.  I think it is a good enough solution for until a bug is reported.

**Comment by bblimke** [comment]
are `extensions` and `subject` the only methods invoked on StubCert or `options` is called as well?

**Comment by bblimke** [comment]
@pboling I guess CN is supposed to match the request hostname?

**Comment by pboling** [comment]
@bblimke I admit I did not look at the underlying implementation.  I only looked at what my client code was calling, and stubbed those.  Those are the two methods I needed for the tests I was writing.  Looking now.

@bblimke, yes, the CN should match.

@bblimke OK, firstly, I removed the hacked mock from my code, and my tests still pass, so I have apparently developed my code beyond needing this hack.

Secondly, I expect the reason it is no longer needed, is the definition of `net-http`'s `peer_cert` method now simply returns an array of strings, and I've upgraded tons of libraries on a 13 year old code base at this point.
```
    # Returns the X509 certificate chain (an array of strings)
    # for the session's socket peer,
    # or +nil+ if none.
    def peer_cert
      if not use_ssl? or not @socket
        return nil
      end
      @socket.io.peer_cert
    end
```
https://github.com/ruby/net-http/blob/e3285bd57a53b19be432c80790c63c8cde0ad6c1/lib/net/http.rb#L1596C1-L1605C1

A modern mock should behave like the modern `peer_cert`!  My hack was needed **transitionally**, as I worked through a maze of library upgrades, but I no longer need it.

**Comment by pboling** [comment]
The relevant repo I'm working on it private, but I just removed the hack, and ran our build matrix against Rails 5.2, 6.0, 6.1, 7.0, 7.1, and 7.2, and Ruby 2.7, 3.1, 3.2, and 3.3.  It works without any hack at all.

IMO it would be good to support returning the array of strings in the SSL scenario.

**Comment by bblimke** [comment]
@pboling thank you for investigating that. Would you be keen to provide a PR with support for returning the array of strings?

**Comment by pboling** [comment]
@bblimke Since I no longer need it, I doubt I'll be able to justify it.  I'd expect that projects testing with SSL Certs validation as part of their specs are few and far between.  This can probably just stay closed, and a motivated person in the future who needs it may stumble over here.

**Comment by bblimke** [comment]
@pboling thank you for explaining!
