### ISSUE TITLE
Rspec matcher(s) missing #description method

### ISSUE THREAD

**Issue by arronmabrey** [bblimke/webmock#501]
Hello,

Under the latest `rspec 3.3.0` and `webmock 1.21.0`

Given the following expectations:

```ruby
specify { expect(WebMock).to have_requested(:get, "http://google.com") }
# or 
specify { expect(a_request(:get, "http://google.com")).to have_been_made }
```

I receive the following Rspec warnings in the test suite ouptput:

```
      should When you call a matcher in an example without a String, like this:

specify { expect(object).to matcher }

or this:

it { is_expected.to matcher }

RSpec expects the matcher to have a #description method. You should either
add a String to the example this matcher is being used in, or give it a
description method. Then you won't have to suffer this lengthy warning again. (FAILED - 1)
```

I would expect webmock to implement the `#description` method for the given Rspec matches.

1. Has this been reported before?
2. Is there any known reason why the `#description` has not or will not be implemented?

Thanks,
-- Arron

**Comment by bblimke** [comment]
@arronmabrey thanks for reporting that.

1) no, it hasn't
2) no good reason 

Would you like to submit a pull request? :)

**Comment by arronmabrey** [comment]
Possibly, I'm occupied for a next week or so, but perhaps after that I can look into it. It should be pretty straight forward I think.

**Comment by arronmabrey** [comment]
I created a PR for this issue here https://github.com/bblimke/webmock/pull/504

**Comment by presidentJFK** [comment]
closing after #511 merged
