### ISSUE TITLE
stubbed HTTParty request's response is nil

### ISSUE THREAD

**Issue by maxjacobson** [bblimke/webmock#522]
I think this may be a bug. Here's a failing test to demonstrate the behavior: https://github.com/bblimke/webmock/compare/master...maxjacobson:stubbed-request-is-nil

**Comment by presidentJFK** [comment]
This is because you did not specify a body to be returned, If you did your test would pass.

Like this:

```ruby
describe 'HTTParty' do
  it "doesn't return nil" do
    req = stub_request(:post, 'http://example.com').to_return(status: 201, body: "response body")
    resp = HTTParty.post('http://example.com')
    expect(resp.success?).to be true

    expect(resp).to_not be_nil
  end
end
```

Does that help?

**Comment by maxjacobson** [comment]
@presidentJFK 

aha! that does help, thanks

It's still a little unexpected but... I can work with that :smile:

**Comment by presidentJFK** [comment]
No prob. I'll look into updating the readme to make this more clear.
