### ISSUE TITLE
webmock 1.22.0 has new un-declared dependency

### ISSUE THREAD

**Issue by frankthrock** [bblimke/webmock#532]
It seems that webmock-1.22.0 has a dependency on the 'rack' module, as seen here:

https://github.com/bblimke/webmock/blob/master/lib/webmock.rb#L33

I don't see rack called out in the .gemspec:

https://github.com/bblimke/webmock/blob/master/webmock.gemspec

**Comment by davidbegin** [comment]
Thanks @frankthrock for reporting this, we have a PR open right now https://github.com/bblimke/webmock/pull/531 where we are working on this, should we fixed soon.

**Comment by frankthrock** [comment]
Thanks!  I really appreciate it!

**Comment by davidbegin** [comment]
@frankthrock the fix is on master now, and we are working on a relase
