### ISSUE TITLE
SOAP urls parsed incorrectly

### ISSUE THREAD

**Issue by NekoNova** [bblimke/webmock#533]
Heya,

There's an issue in the latest version of webmock.
All WSDL urls for SOAP services get appended with an `WSDL=true`.

I had to revert webmock to `gem 'webmock', '~> 1.17.4'` to get it to work again.

**Comment by bblimke** [comment]
@NekoNova WebMock is not appending this on it's own. Perhaps one of the libs has changed. Do you see any other gems upgraded in Gemfile.lock when you upgraded WebMock to the latest version?

**Comment by NekoNova** [comment]
not really. I first placed the blame inside VCR and Faraday, but after digging deeper, I came with the Stacktraces down to Webmock.

We only use Webmock and Faraday in our RSpec, I can try checking again in the pull-request, but as far as I know we have no dependencies.

**Comment by NekoNova** [comment]
only gem I saw change on the revert was `addressable`

**Comment by bblimke** [comment]
and webmock 1.18.0 also causes problems?

**Comment by NekoNova** [comment]
let me try to switch to 1.18.0, give me a second

**Comment by NekoNova** [comment]
it doesn't let me install that one.
It's either the 1.17 or the 1.21 version for some reason.

Also it seems when addressable swaps from 2.2 to 2.3 it breaks with VCR as the bug then occurs.

**Comment by bblimke** [comment]
it's worth checking where the WSDL=true comes from. not from WebMock, I don't think from addressable either. Perhaps from your code or SOAP lib you use?

**Comment by NekoNova** [comment]
`webmock` 1.18.0 works sorry. this is in combination with `addressable` `2.3.8`.

For Soap we use the latest `Savon` which has not been changed in a while.
This thing is.....weird to say the least

**Comment by mislav** [comment]
I think it may come from Faraday and that https://github.com/lostisland/faraday/issues/536 is legit.

**Comment by NekoNova** [comment]
let's continue the discusssion there then :)
