### ISSUE TITLE
Multiple HTTP responses not working

### ISSUE THREAD

**Issue by maclover7** [bblimke/webmock#545]
Hi,

I was reading the docs in the README.md for returning multiple HTTP responses, but it appears to be broken for me. A code example is available [here](https://github.com/maclover7/globe-v2/blob/create-users/spec/support/webmock.rb#L19), where the two different bodies are defined. You can run the test suite in that repo (via `rake`), and I made it so for debugging purposes in this issue, it would `puts` out the value that's supposed to be changing. Any help would be appreciated. :)

**Comment by bblimke** [comment]
@maclover7 I get 404 when I try to access the code

**Comment by maclover7** [comment]
Weird -- here's the code example. When I run the request twice (this is being run via the rack-test gem, not sure if that has any effect) only the first response (the one with bad) is returned.

```ruby
stub_request(:post, 'https://www.googleapis.com/oauth2/v3/token')
  .with(body: 'client_id=blah&client_secret=blah&code=bad&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin')
  .to_return(
    body: '{"access_token":"bad!"}',
    body: '{"access_token":"good!"}',
    status: 200,
    headers: { 'Content-Type' => 'application/json' }
)
```

**Comment by bblimke** [comment]
As far as I can see you declare only one response. There is only one hash passed to `to_return` method.

You probably want the following:
```ruby
stub_request(:post, 'https://www.googleapis.com/oauth2/v3/token')
  .with(body: 'client_id=blah&client_secret=blah&code=bad&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin')
  .to_return(
   {
    body: '{"access_token":"bad!"}',
    status: 200,
    headers: { 'Content-Type' => 'application/json' }
  },
  {
    body: '{"access_token":"good!"}',
    status: 200,
    headers: { 'Content-Type' => 'application/json' }
  }
)
```

**Comment by maclover7** [comment]
Ok -- that makes sense to me. Does the documentation on the README.md need to be updated then? That's where I looked to get the (now wrong) answer: https://github.com/bblimke/webmock#multiple-responses-for-repeated-requests

**Comment by bblimke** [comment]
What's wrong with documentation? Where is the wrong answer? It clearly shows two hashes passed to `to_return` method.

**Comment by maclover7** [comment]
Whoops -- my bad. I misinterpreted your answer -- documentation is :+1:. Thanks for solving this problem -- all set to close out the issue?

**Comment by bblimke** [comment]
I'm glad your problem is solved :)
