### ISSUE TITLE
Suppressing request_signature?

### ISSUE THREAD

**Issue by tombh** [bblimke/webmock#553]
I just got caught out with an `Unregistered request: GET https://username:password@example.com` getting logged on Travis with decrypted sensitive credentials. Is there any way to suppress the logging of URLs like that? Surprised that I'm the first person to have this problem, I must be doing something wrong!

**Comment by bblimke** [comment]
Basic auth credentials are not encrypted. They are just base64 encoded. I assume you have a private Travis project, not a public one?

There is a way to suppress that logging. Either by allowing real requests to that url or by stubbing it. If there is no error, there will be no logging.

**Comment by tombh** [comment]
OMG 9 years, and only now do I notice your reply!!! Thank you for taking the time to answer me all those years ago.
