### ISSUE TITLE
Error in curl reader on Ruby 2.3

### ISSUE THREAD

**Issue by cpence** [bblimke/webmock#558]
On Ruby 2.3.0, latest webmock, I'm getting a `TypeError: no implicit conversion of Hash into String`. I can see from debug prints that it's raising from the call to `Net::HTTPResponse.read_new` [right here,](https://github.com/bblimke/webmock/blob/master/lib/webmock/response.rb#L129) though I can't get real backtraces as it's going into gem files.

I can confirm that `raw_response` is a String, as expected, and this exact same code worked on Ruby 2.2.3. Maybe a change in behavior on `read_new`?

**Comment by cpence** [comment]
(Sorry, posted early, editing now)

**Comment by davidbegin** [comment]
Thanks for submitting this!

I think you are on the right track.
ruby-head has been failing on Travis for a while with this exact error message, and I haven't had time to explore.

 But if you want to take a crack at figuring out the details and getting a fix together, I'll help in whatever way I can.

If not I will try tacking a crack at this once I get some other issues resolved first.

**Comment by cpence** [comment]
I'm on the trail now; will report back soon.

**Comment by cpence** [comment]
Okay, I know what's causing this, but I have *no* idea how to fix it in WebMock. [This commit](https://github.com/ruby/ruby/commit/db2ff03bc0f87df5ec699d3d3d0f9c58c7d114fb) to the Ruby stdlib means that `BufferedIO#rbuf_fill` calls `@io.read_nonblock(BUFSIZE, exception: false)`.

This works fine when `@io` is a real `IO`. Problem is, the method signature for `StringIO#read_nonblock` is ([check it here](https://github.com/ruby/ruby/blob/f4166e2dd7a4d9be95f160e19303ddeeb5d27ab4/ext/stringio/stringio.c#L1348)):

```
strio.read_nonblock(integer[, outbuf [, opts]])    -> string
```

I don't know what exactly that `outbuf` parameter is, as it's not documented anywhere in the Ruby stdlib docs (thanks, stdlib), but it looks like you can pass in a string to use as the output buffer. That means that the `BufferedIO` code is calling `StringIO#read_nonblock` with the wrong parameters when `WebMockNetBufferedIO` sets `@io` to a `StringIO`.

**Comment by cpence** [comment]
Got it! Add the following monkey patch to `net_http.rb`, right above `StubSocket`:

```ruby
class PatchStringIO < StringIO #:nodoc:

  alias_method :orig_read_nonblock, :read_nonblock

  def read_nonblock(size, *args)
    orig_read_nonblock(size)
  end

end
```

In `WebMockNetBufferedIO`, change the `StringIO.new` call to `PatchStringIO.new`. Fixed! And the fix should be back-compatible to 2.2.

**Comment by davidbegin** [comment]
awesome! that was fast, want to open a PR?

**Comment by cpence** [comment]
Will do.

**Comment by davidbegin** [comment]
closing now that #561 is merged in. Thanks @cpence!
