### ISSUE TITLE
stub_request return a hash in rspec

### ISSUE THREAD

**Issue by VoTaiTri** [bblimke/webmock#572]
when i fakeweb for rspec test, i have code like that : 
```ruby
stub_request(:get, uri).with(query: request_params)
  .to_return(
    status: 200,
    body: expected_body
  )
```
and i want to `expected_body` like a hash:
```ruby
{
   "result" => 1,
   "kojinIdInfos" =>
   [
     {
        "stdtId" => "STG1U18311",
        "beneId" => "AA"
     }
   ]
}
```
i see
```
WebMock::Response::InvalidBody:
    must be one of: [Proc, IO, Pathname, String, Array]. 'Hash' given
```
so, can i do it?
can i return `json` data instead `hash`?
i need your help!

**Comment by bblimke** [comment]
Hash is not accepted as response body, as there is no way to know how it should be encoded.

If you expect json, please use json I.e `expected_body.to_json` or `JSON.generate(expected_body)`

Depending on http client you use, you may also want to add correct content-type header to the stubbed response, so the client knows how to parse the response.

**Comment by VoTaiTri** [comment]
@bblimke
i got it
thanks you for answer
