### ISSUE TITLE
Order of gems in test gem group matters when running 'bundle exec rake'

### ISSUE THREAD

**Issue by gthorsen** [bblimke/webmock#576]
I noticed that if you place webmock gem before your travis gem it causes webmock to throw a WebMock::NetConnectNotAllowedError after running a 'bundle exec rake', complaining that the api,travis-ci,org site cant be called. 

Placing webmock at the end of the gem list in the test gem group fixed the problem.   Figured I'd share in case this behavior was not intentional.

**Comment by bblimke** [comment]
WebMock prevents any connections by default and it's intentional. Travis most likely tries to make some http connection when loaded.

**Comment by beechnut** [comment]
It seems like this issue is directly related to / arguably a subset of #583.

**Comment by bblimke** [comment]
Interesting. Does it mean travis gem makes a http request on load?
