### ISSUE TITLE
invalid byte sequence in UTF-8 with File object in body

### ISSUE THREAD

**Issue by 6temes** [bblimke/webmock#580]
I have this code that I need to test:

```ruby
HTTPClient.new.post_content('some URL', type: 'image', file: File.open('some file path'))
```

I tried to mock the connection with this:

```ruby
stub_request(:post, 'some URL')
      .with(body: hash_including(type: 'image'))
      .to_return(body: { result: 'success' }.to_json)
```

But I get an exception with the text `ArgumentError: invalid byte sequence in UTF-8`.

Is this an expected behaviour? If yes, is there any way I could stub this without changing the original code?

**Comment by bblimke** [comment]
Can you provide the full backtrace?

**Comment by 6temes** [comment]
This is the backtrace.

```ruby
Failure/Error: described_class.new(attributes).execute
 ArgumentError:
   invalid byte sequence in UTF-8
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/util/query_mapper.rb:73:in `split'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/util/query_mapper.rb:73:in `collect_query_parts'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/util/query_mapper.rb:54:in `query_to_values'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/request_pattern.rb:240:in `body_as_hash'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/request_pattern.rb:220:in `matches?'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/request_pattern.rb:34:in `matches?'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/stub_registry.rb:57:in `each'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/stub_registry.rb:57:in `detect'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/stub_registry.rb:57:in `request_stub_for'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/stub_registry.rb:50:in `response_for_request'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/httpclient_adapter.rb:205:in `block in webmock_responses'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/httpclient_adapter.rb:59:in `yield'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/httpclient_adapter.rb:59:in `do_get'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/httpclient_adapter.rb:47:in `do_get_block'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/httpclient-2.6.0.1/lib/httpclient.rb:1053:in `follow_redirect'
 # /Users/user/.rbenv/versions/2.2.3/gemsets/-global/gems/httpclient-2.6.0.1/lib/httpclient.rb:667:in `post_content'
 # ./app/models/example/provider.rb:17:in `request'
```

**Comment by riyad** [comment]
Assuming a setup like this

```ruby
url = "https://example.com/something"
name = "foo.pdf"
task_id = "bar"

attachment = ActionDispatch::Http::UploadedFile.new({
  filename: name,
  type: 'application/pdf',
  tempfile: File.new("#{Rails.root}/spec/fixtures/#{name}")
})

RestClient.post(url, { upload: { file: File.new(attachment.path, 'rb') } })
RestClient.post(url, { upload: { file: File.new(attachment.path, 'rb') }, task_id: task_id })
```

simple rspec tests work:

```ruby
expect(a_request(:post, url)).to have_been_made.twice
```

Tests that check the content of the requests like

```ruby
expect(WebMock).to have_requested(:post, url).with(task_id: task_id)
```

work with webmock < 1.20.3. Later versions produce the following error:

    ArgumentError:
        Unknown key: "task_id". Valid keys are: "body", "headers", "query"

Trying to fix it with

```ruby
expect(WebMock).to have_requested(:post, url).with(body: hash_including({task_id: task_id}))
```

fails with

    ArgumentError:
     invalid byte sequence in UTF-8
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/util/query_mapper.rb:73:in `split'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/util/query_mapper.rb:73:in `collect_query_parts'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/util/query_mapper.rb:54:in `query_to_values'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_pattern.rb:240:in `body_as_hash'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_pattern.rb:220:in `matches?'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_pattern.rb:34:in `matches?'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_registry.rb:18:in `block in times_executed'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_registry.rb:17:in `select'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_registry.rb:17:in `times_executed'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/request_execution_verifier.rb:15:in `matches?'
    # ~/.gem/ruby/2.3.0/gems/webmock-1.24.2/lib/webmock/rspec/matchers/webmock_matcher.rb:30:in `matches?'

**Comment by leemour** [comment]
Same issue, when using `have_requested(:post, url).with(body: { file: File.new(path) })`

**Comment by bblimke** [comment]
@riyad `expect(WebMock).to have_requested(:post, url).with(task_id: task_id)` did not work in earlier versions than 1.20.3. task_id was simply ignored.

**Comment by riyad** [comment]
@bblimke good to know 😅

**Comment by bblimke** [comment]
There are two underlying issues.

First issue is that WebMock doesn't handle multipart body. 

Second issue is that WebMock doesn't handle binary content in body.

I can find a solution for the binary content, but multipart is tricky.

I.e File object is split into multiple headers and then body.

It's not something that can be easily fixed.

I guess for now it makes sense at least to raise an error, so that nobody wastes time on debugging the 
'invalid byte sequence in UTF-8' error.

**Comment by bblimke** [comment]
"Second issue is that WebMock doesn't handle binary content in body." - to clarify, is does support binary body, but only if the whole body is a binary content.

The only problem is with multipart body.

**Comment by bblimke** [comment]
I changed the behaviour so that error message is raised on an attempt to match multipart request body.

This solves the ambiguous 'invalid byte sequence in UTF-8' error issue.

Multipart body support is a separate issue.

**Comment by riyad** [comment]
Thanks. Unambiguous error messages are a start. 😀
