### ISSUE TITLE
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST with `NET::GTTP`

### ISSUE THREAD

**Issue by VoTaiTri** [bblimke/webmock#584]
Dear,
i'm doing with webmock to fake api
that when i send request to `api`, with `body: request_params`, i wish to receive a response `expected_body`
so code like that:
```ruby
stub_request(:post, api)
  .with(body: request_params)
  .to_return(
    status: 200,
    body: expected_body.to_json
  )
```
 and i use `Net::HTTP` to call it in:
```ruby
url = URI.parse(Settings.api)
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.ca_file = "#{Rails.root}#{Settings.ca_file}"
http.verify_mode = OpenSSL::SSL::VERIFY_PEER

response = http.post(url.path, URI.encode_www_form(request_params)) # error here
```
i get error
`WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST`
so, do you know about this error?
i need your help
thanks

**Comment by bblimke** [comment]
Can you provide more details on the error? The WebMock::NetConnectNotAllowedError error message provides more information. 

Have you tried stubbing with `.with(body: URI.encode_www_form(request_params))` ?

**Comment by VoTaiTri** [comment]
this's error:
```Ruby
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/?daihyoCd=57a70&jissiGakunen=C1&stdtIds=STG1U18312 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'fifr901x6.bc-extra.net', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:

stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/?daihyoCd=57a70&jissiGakunen=C1&stdtIds=STG1U18312").
  with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'fifr901x6.bc-extra.net', 'User-Agent'=>'Ruby'}).
  to_return(:status => 200, :body => "", :headers => {})

registered request stubs:

stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").
  with(:body => {"daihyoCd"=>"57a70", "jissiGakunen"=>"C1", "stdtIds"=>["STG1U18311", "STG1U18312"]})
```
i stub like that:
```Ruby
stub_request(:post, Settings.api)
  .with(body: request_params)
  .to_return(
    status: 200,
    body: expected_body.to_json
  )
```
with 
- `api` like `https://...`
- `request_params` is a hash

**Comment by VoTaiTri** [comment]
@bblimke 
when i try stubbing like
```Ruby
.with(body: URI.encode_www_form(request_params))
```
it's ok
thank you very much :+1:

**Comment by bblimke** [comment]
The problem is that you have two parameters with the same name in your url encoded body, which is not something webmock supports by default. 

````
irb(main):003:0> URI.encode_www_form({"stdtIds"=>["STG1U18311", "STG1U18312"]})
=> "stdtIds=STG1U18311&stdtIds=STG1U18312"
````

You can change the default data structure used to represent urls in WebMock.

````
WebMock::Config.instance.query_values_notation = :flat_array
````

That should work with duplicate params.

**Comment by VoTaiTri** [comment]
@bblimke 
currently, i have file : `spec/support/webmock.rb`
```ruby
require 'webmock/rspec'

WebMock.disable_net_connect!(allow: 'codeclimate.com')
```
and i have no folder `lib/webmock`
so, where can i write this line?
```ruby
WebMock::Config.instance.query_values_notation = :flat_array
```

**Comment by bblimke** [comment]
put it below `WebMock.disable_net_connect!(allow: 'codeclimate.com')`

**Comment by VoTaiTri** [comment]
when i do it
can i stub like
```ruby
.with(body: request_params)
```
instead
```ruby
.with(body: URI.encode_www_form(request_params))
```
and call by
```ruby
response = http.post(url.path, URI.encode_www_form(request_params))
```
???

**Comment by bblimke** [comment]
yes, that should work

**Comment by VoTaiTri** [comment]
@bblimke 
i don't know why but when i try to do that
i get error
```ruby
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/ with body 'daihyoCd=a6d34&jissiGakunen=C1&stdtIds=STG1U18311&stdtIds=STG1U18312' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}
       
       You can stub this request with the following snippet:
       
       stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").
         with(:body => "daihyoCd=a6d34&jissiGakunen=C1&stdtIds=STG1U18311&stdtIds=STG1U18312",
              :headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
         to_return(:status => 200, :body => "", :headers => {})
       
       registered request stubs:
       
       stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").
         with(:body => {"daihyoCd"=>"a6d34", "jissiGakunen"=>"C1", "stdtIds"=>["STG1U18311", "STG1U18312"]})

```

**Comment by bblimke** [comment]
I'd have to look deeper into this and investigate.

Please use `.with(body: URI.encode_www_form(request_params))` if that works for you.

**Comment by VoTaiTri** [comment]
Thank you for your support!!!

**Comment by VoTaiTri** [comment]
@bblimke 
can you help me about that
as you know
i have rspec to test upload method like that: 
```ruby
describe "POST #upload" do
  before do
    stub_request(:post, api)
      .with(body: URI.encode_www_form(request_params))
      .to_return(
        status: 200,
        body: "hello"
      )

    post :upload
  end

  it {...}
end
```
and controller
```ruby
def upload
  ...
  url = URI.parse(api)
  http = Net::HTTP.new(url.host, url.port)
  http.use_ssl = true
  http.ca_file = "#{Rails.root}#{Settings.try(:bhso).try(:ca_file)}"
  http.verify_mode = OpenSSL::SSL::VERIFY_PEER

  response = http.post(url.path, URI.encode_www_form(request_params)) # failure here
  ...
end
```
heretofore, it was ok
but currently, i get error like i've mentioned above:
```
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/ with body 'daihyoCd=fc074&jissiGakunen&stdtIds=STG1U18311&stdtIds=STG1U18312' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}
       
       You can stub this request with the following snippet:
       
       stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").
         with(:body => "daihyoCd=fc074&jissiGakunen&stdtIds=STG1U18311&stdtIds=STG1U18312",
              :headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
         to_return(:status => 200, :body => "", :headers => {})
       
       registered request stubs:
       
       stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").
         with(:body => "daihyoCd=fc074&jissiGakunen=C1&stdtIds=STG1U18311&stdtIds=STG1U18312")
```
It is OK if i use `Webmock` in controller to stubbing like that:
```ruby
  require "webmock"
  include WebMock::API

  def upload
  ...
    stub_request(:post, Settings.bhso.api)
      .with(body: URI.encode_www_form(request_params))
      .to_return(
        status: 200,
        body: "hello"
      )

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.ca_file = "#{Rails.root}#{Settings.try(:bhso).try(:ca_file)}"
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    response = http.post(url.path, URI.encode_www_form(request_params)) # OK
  ...
  end
```
thanks!

**Comment by bblimke** [comment]
@VoTaiTri the stub and requests are different. in stubbed body you have `jissiGakunen=C1` and in requested body `jissiGakunen`. the `=C1` is missing.

**Comment by VoTaiTri** [comment]
thanks you for your suggestion
@bblimke

**Comment by msdundar** [comment]
```ruby
test 'Başarılı işlem sonunda cevaplar veritabanına kaydedilmeli' do
      stub_request(:post, 'https://www.wirecard.com.tr/services/DirectCCSaleService.asmx')
        .with(body: @xml.to_s)
        .to_return(status: 200, body: ThreePay::Res.template('add_credit_card.erb', @params))

      service = Payments::AddCreditCardService.new(@params)
      service.call

      assert service.add_credit_card.success?
      assert_equal service.add_credit_card.bank_name, 'Garanti Bankası'
      assert_equal service.add_credit_card.cc_sale_key, '1234'
      assert_equal service.add_credit_card.masked_credit_card_no, '************1789'
      assert_equal service.add_credit_card.status_code, 0
end
```

**Returns =>**

```
You can stub this request with the following snippet:

stub_request(:get, "https://www.wirecard.com.tr/services/DirectCCSaleService.asmx?wsdl").
  with(:headers => {'Host'=>'www.wirecard.com.tr:443'}).
  to_return(:status => 200, :body => "", :headers => {})

registered request stubs:

stub_request(:post, "https://www.wirecard.com.tr/services/DirectCCSaleService.asmx").
  with(:body => "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap12:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap12=\"http://www.w3.org/2003/05/soap-envelope\">\n  <soap12:Body>\n    <AddCreditCard xmlns=\"https://www.3pay.com/services\">\n      <token>\n        <UserCode></UserCode>\n        <Pin></Pin>\n      </token>\n      <input>\n        <CustomerId>621144132</CustomerId>\n        <CardName>B</CardName>\n        <CreditCardNo>C</CreditCardNo>\n        <OwnerName>D</OwnerName>\n        <ExpireYear>17</ExpireYear>\n        <ExpireMonth>8</ExpireMonth>\n        <Cvv>123</Cvv>\n      </input>\n    </AddCreditCard>\n  </soap12:Body>\n</soap12:Envelope>\n\n")
```

**Comment by bblimke** [comment]
@msdundar your stub is for `https://www.wirecard.com.tr/services/DirectCCSaleService.asmx` and  the request is for `https://www.wirecard.com.tr/services/DirectCCSaleService.asmx?wsdl`.
Please note the `?wsdl` suffix.

**Comment by mohitgpt24** [comment]
@bblimke how to stub the POST request where body and headers have timestamps?

**Comment by bblimke** [comment]
@mohitgpt24 you can just ignore the headers if you don't care about them.

alternatively you can match the whole request against block, which returns either true or false.

https://github.com/bblimke/webmock#matching-requests-against-provided-block

**Comment by blayvant** [comment]
I am getting an error even though the request seems to fully match the expected parameters: 

Real HTTP connections are disabled. Unregistered request: POST http://localhost/response_nudges with body 'phone_number=1234567181&expected_response=Test' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:
 stub_request(:post, "http://localhost/response_nudges").
 with(body: "phone_number=1234567181&expected_response=Test", headers: {'Accept'=>'*/*', 
 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
 to_return(status: 200, body: "", headers: {})

 registered request stubs:
 stub_request(:post, "http://localhost/response_nudges").
 with(body: "phone_number=1234567181&expected_response=Test")

Rspec test code:

`request_querystring = "phone_number=1234567181&expected_response=Test"`
`stub_request(:post, "http://localhost/response_nudges").with(body: request_querystring).to_return(status: 200, body: "", headers: {})`
`HTTParty.post "http://localhost/response_nudges", body: request_querystring`

**Comment by bblimke** [comment]
@blayvant it does work for me:

````
require 'webmock'
require 'httparty'

WebMock.enable!
include WebMock::API

request_querystring = "phone_number=1234567181&expected_response=Test"
stub_request(:post, "http://localhost/response_nudges").with(body: request_querystring).to_return(status: 200, body: "abc", headers: {})
p HTTParty.post("http://localhost/response_nudges", body: request_querystring).body
=> "abc"
````

**Comment by blayvant** [comment]
The code works for me in the rails console as well, but not in an Rspec test.

`it "test request" do`
    `request_querystring = "phone_number=1234567181&expected_response=Test"
     stub_request(:post, "http://localhost/api/response_nudges").with(body: 
      request_querystring).to_return(status: 200, body: "", headers: {})`
     `HTTParty.post "http://localhost/api/response_nudges", body: request_querystring`
`end`

The above spec returns the previously reported error.

However, when the URL is a regular expression instead of a string, the test passes:

 ` it "test request" do`
    `request_querystring = "phone_number=1234567181&expected_response=Test"
    stub_request(:post, /localhost\/api\/response_nudges/).with(body: request_querystring).to_return(status: 200, body: "", headers: {})`
    `HTTParty.post "http://localhost/api/response_nudges", body: request_querystring`
  `end`

**Comment by bblimke** [comment]
by console do you mean rails console in development environment or test environment?
If development, then could you please try the console in test environment,
to ensure the issue is not specific to your test environment only?

You can try generating an empty Rails app with rspec and add a single spec example there,
to ensure the issue is not related to your environment.

If you can reproduce it on that empty rails app, please share that empty rails project.

**Comment by Hmanshudweevedee** [comment]
Failure/Error: Pusher.trigger('lct', 'rate', {data: {highest_bid: self.price, lowest_ask: Order.where(order_type: "ask").last.try(:price)}})
      
      WebMock::NetConnectNotAllowedError:
        Real HTTP connections are disabled. Unregistered request: POST https://api-ap2.pusher.com/apps/469526/events?auth_key=3f4a26ef50aaf34126b5&auth_signature=5f05012a06fcba807112a0c4cb455d9480af532d93390171a3c158cb8fed9d58&auth_timestamp=1519282649&auth_version=1.0&body_md5=a7916b21d264220845a121089984e237 with body '{"name":"rate","channels":["lct"],"data":"{\"data\":{\"highest_bid\":\"1.0\",\"lowest_ask\":null}}"}' with headers {'Accept'=>'*/*', 'Content-Type'=>'application/json', 'Date'=>'Thu, 22 Feb 2018 06:57:29 GMT', 'User-Agent'=>'HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))', 'X-Pusher-Library'=>'pusher-http-ruby 1.3.1'}
      
        You can stub this request with the following snippet:
      
        stub_request(:post, "https://api-ap2.pusher.com/apps/469526/events?auth_key=3f4a26ef50aaf34126b5&auth_signature=5f05012a06fcba807112a0c4cb455d9480af532d93390171a3c158cb8fed9d58&auth_timestamp=1519282649&auth_version=1.0&body_md5=a7916b21d264220845a121089984e237").
          with(body: "{\"name\":\"rate\",\"channels\":[\"lct\"],\"data\":\"{\\\"data\\\":{\\\"highest_bid\\\":\\\"1.0\\\",\\\"lowest_ask\\\":null}}\"}",
               headers: {'Accept'=>'*/*', 'Content-Type'=>'application/json', 'Date'=>'Thu, 22 Feb 2018 06:57:29 GMT', 'User-Agent'=>'HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))', 'X-Pusher-Library'=>'pusher-http-ruby 1.3.1'}).
          to_return(status: 200, body: "", headers: {})




please help how i can write stub for this error

**Comment by muratatak77** [comment]
```
WebMock.allow_net_connect!
```

and works for me.

**Comment by Iank-code** [comment]
Hey @VoTaiTri 

To fix this, don't use this
`stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/?daihyoCd=57a70&jissiGakunen=C1&stdtIds=STG1U18312").`

Instead use this
`stub_request(:post, "https://fifr901x6.bc-extra.net/schoolas/api_open/CLA003/").`
