### ISSUE TITLE
Update Curb gem version?

### ISSUE THREAD

**Issue by timhaines** [bblimke/webmock#585]
I noticed Curb is pinned to 0.8.6, when 0.9.1 is out.  I've tried cloning webmock and ran the specs against 0.9.1 and they all passed successfully.  I only ran the specs against my ruby 2.3.0 install though, using `bundle exec rspec spec/**/*_spec.rb`.

I noticed this commit locked curb's version to 0.8.6: https://github.com/bblimke/webmock/commit/f1cfb183f30a657e139c8a32c745309424b2f30b

Can webmock be safely updated to use Curb 0.9.1?

**Comment by bblimke** [comment]
Thanks for raising this. I just released version 1.24.0 with allows latest Curb to be used.

**Comment by timhaines** [comment]
Thank you!

Closing this as fixed in v 1.24.0.    https://github.com/bblimke/webmock/commit/162136153df3f87e542b0a62f05d4e178552f1e5
