### ISSUE TITLE
Hash rocket at webmock snippet

### ISSUE THREAD

**Issue by MarceloCajueiro** [bblimke/webmock#589]
Hello,

Can I open a PR to improve the snippet printed when a test is broken raising `WebMock::NetConnectNotAllowedError`?

The major part of the ruby projects have replaced the hash rocket so I thing that would be nice to print using the "new" format

``` ruby
# This
stub_request(:get, "https://example.com").
  with(headers: { 'Accept'=>'application/json' }).
  to_return(status: 200, body: "", headers: {})

# Instead of this
stub_request(:get, "https://example.com").
  with(:headers => {'Accept'=>'application/json'}).
  to_return(:status => 200, :body => "", :headers => {})
```

Is it unnecessary complexity?

**Comment by bblimke** [comment]
sure, feel free to open a PR. you can replace other examples as well if there are any.

**Comment by tamgrosser** [comment]
solved via https://github.com/bblimke/webmock/pull/669 ... please close @bblimke

**Comment by bblimke** [comment]
@tamgrosser thanks for pointing out!
