### ISSUE TITLE
HTTPClient Basic authentication header handling is weird since v1.24.1

### ISSUE THREAD

**Issue by nov** [bblimke/webmock#591]
This block didn't raise any error before, but it raises `WebMock::NetConnectNotAllowedError` since 1.24.1.
It seems userinfo is set in the stub request wrong way.

``` ruby
require 'webmock'
include WebMock::API

WebMock.disable_net_connect!

endpoint = 'http://auth.example.com/'
headers = {
  'Authorization': 'Basic Y2xpZW50X2lkOmNsaWVudF9zZWNyZXQ'
}

stub_request(:post, endpoint).with(
  headers: headers
)

HTTPClient.post(endpoint, nil, headers)
```

**Comment by bblimke** [comment]
@nov thank you for reporting this.

@mkarnebeek any thoughts?

**Comment by mkarnebeek** [comment]
It depends what the idea is behind handling basic auth.

- When supplying credentials in the URI,  it is clear the mock should also have it in the URI. 
- When supplying credentials via de http client's api (for example HTTPClients's basic_auth method on a client), it's unclear if the mock should have the credentials in the URI. Judging from existing WebMock implementation of other http clients, it should be in de URI. (i think it is even in the specs) 
- When supplying headers, it's probably up for discussion. My previous PR changed this behavior to be consistent with the above two, but there is also something to be said to have the mock "as close to the original call", in which case the credentials should not be in the URI. 

I'm currently on vacation and will be back the 16th this month (a week from now). Let me known if i can be of any help then.

**Comment by mkarnebeek** [comment]
As for the third case, we should also look how WebMock implements this for other http client libraries.

**Comment by bblimke** [comment]
With the fact that basic authentication can be specified in 2 different ways (url or header) it's tricky indeed. 

Perhaps WebMock could treat Authorization header and credentials in the url as equal (both ways, currently it's only one way). In case it's important that the request has authorization header, the behaviour would be wrong.

**Comment by nov** [comment]
```ruby
endpoint = 'http://auth.example.com/'
headers = {
  'Authorization': 'Basic Y2xpZW50X2lkOmNsaWVudF9zZWNyZXQ'
}

stub_request(:post, endpoint).with(
  headers: headers
)
```
HTTPClient.post(endpoint, nil, headers)
```

**Comment by bblimke** [comment]
@nov I have been thinking about it and I agree that the current solution is confusing.

The simplest solution would be to not remove the Authorization headers from the request signature.
This will allow making expectations on request headers in stubs.

Unfortunately, WebMock will still extract the header, decode it and add the userinfo to the url.
That's the current behaviour and removing it would break backward compatibility.

This has additional side effect that the stub without userinfo specified, is not going
to match a request signature with userinfo present (and it will be added to request signature, as mentioned above).

To have a matching stub, one will have to add userinfo to the url anyway,
despite declaring expected authorization header in the stub headers already.

This will make things complex.

I'm considering removing this whole mess. Keeping userinfo in url completely separate to authorization headers, breaking backward compatibility and upgrading WebMock to version 2.0.0.

This will require programmes to create stubs with base64 encoded version of the username and password, which won't be as readable, but perhaps that's the way right way to do it.

Any thoughts? 

//cc @upuls @sirn

**Comment by bblimke** [comment]
For reference https://github.com/bblimke/webmock/issues/593

**Comment by nov** [comment]
Fixing in next major version is fine for me :)
I'm not understanding why things were OK before 1.24.1 yet though.

**Comment by bblimke** [comment]
It worked because Authorization header was ignored by WebMock's HTTPClient adapter, unless credentials were set with `set_basic_auth`

**Comment by sirn** [comment]
Having 2.0.0 leave authorization header as-is separate from userinfo sounds good to me.

One of the pattern I did quite often is when I need to stub a request that happen to contain authorization header that I'm not actually cared (since authorization is done by other components), I found myself to do a lot of stubbing using Regex URL to get around the userinfo. 

In either case, I'm very much prefer if WebMock do not transform the request and treat userinfo and authorization header separately (userinfo only if it is in the URL, leave it in header if it is in the header).

**Comment by bblimke** [comment]
@nov Could you please check if version 2.0.0.beta1 resolves this issue? Please see the changes here https://github.com/bblimke/webmock/blob/2.0/CHANGELOG.md#200

@nov @sirn @uplus Version 2.0 is backwards incompatible with version 1.x. Do you find the information in the CHANGELOG sufficient?

**Comment by nov** [comment]
cool, `2.0.0.beta1` works perfect for my gem ;-)

**Comment by upuls** [comment]
Yes, the change log details are sufficient to go by. Will give it a try and
report back if we hit a snag

Thanks!

**Comment by sirn** [comment]
The changelog is clear enough to me, but I think it would be nice if "Important! Since version 2.0.0…" in 2.0.0 README is moved to the "Upgrading…" section (since now it's kinda buried inside the examples.)
