### ISSUE TITLE
Possible bug with `hash_including`

### ISSUE THREAD

**Issue by tomprats** [bblimke/webmock#594]
When I first saw `hash_including` in the docs it was pretty exciting that it seemed to be exactly what I wanted. On further testing it looks like it's not working. Here is the output:

```
 WebMock::NetConnectNotAllowedError:
   Real HTTP connections are disabled. Unregistered request: POST https://api.stripe.com/v1/tokens with body 'card[address_zip]=21224&card[cvc]=123&card[exp_month]=12&card[exp_year]=2030&card[name]=John+Doe&card[number]=4242424242424242' with headers {removed for brevity}

   You can stub this request with the following snippet:

   stub_request(:post, "https://api.stripe.com/v1/tokens").
     with(:body => {"card"=>{"address_zip"=>"21224", "cvc"=>"123", "exp_month"=>"12", "exp_year"=>"2030", "name"=>"John Doe", "number"=>"4242424242424242"}},
          :headers => {removed for brevity}).
     to_return(:status => 200, :body => "", :headers => {})

   registered request stubs:

   stub_request(:post, "https://api.stripe.com/v1/tokens").
     with(:body => hash_including({"card"=>{"number"=>"4242424242424242"}}))
```

My first confusion was why it has an empty body for the `to_return`, but ignoring that, I'm not sure why my stub wouldn't catch the request. On further testing, my stub worked if I add the rest of the fields (with or without hash_including).

This seems like a very similar use case as the readme, but I can't figure out why it wouldn't work unless I include the full hash

Webmock: 1.24.2
Rails: 4.2.0
Rspec: 3.4.0

**Comment by acorncom** [comment]
Works for me if I do this:

```rb
   stub_request(:post, "https://api.stripe.com/v1/tokens").
     with(:body => hash_including({card: {number: "4242424242424242"}}))
```

**Comment by taylor19882002** [comment]
I met similar problem,  hash_including is not supporting nested hash ? https://github.com/bblimke/webmock/pull/416

**Comment by bblimke** [comment]
@taylor19882002 can you please provide a failing example?

**Comment by taylor19882002** [comment]
stub = stub_request(:post, "url/")
               .with(:body => hash_including("query"),
                     :headers => mock_headers)
               .to_return(:status => 200, :body => mock_response.to_json.to_s, :headers => {})

**Comment by bblimke** [comment]
@taylor19882002 ok, I'll investigate when I find some time, unless someone investigates that before.

**Comment by redbar0n** [comment]
This works for me:

    partial_body = { a: 123, b: { c: 'string' , d: 'string', e: 'string' } }
    stub_request(:post, "http://example.com/apiendpoint").
      with(:body => hash_including(partial_body),
           :headers => {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip, deflate', 'Content-Type'=>'application/json'}).
      to_return(:status => 200, :body => "{}", :headers => {})

but using `hash_including(partial_body.to_json)` didn't work.

NB: Note that `hash_including` expects that the `partial_body` hash matches the body in an exact sequential order, although not necessarily from the beginning. Meaning that `a: 123,` could be excluded, but not `d: 'string',`. Ref: some other open issue I saw here, regarding how `hash_include` does the matching.

**Comment by bblimke** [comment]
@redbar0n I'm not sure if `hash_including(partial_body.to_json)` could work. `partial_body.to_json` is a string, right?

**Comment by redbar0n** [comment]
@bblimke Yes, you're right. It's a string, so it couldn't possibly work. I must have thought the `hash_including` parsed the json or something, but it makes sense that it doesn't.

**Comment by tomprats** [comment]
So it looks like my original problem was just a misunderstanding of `hash_including`. It looks like nesting an additional `hash_including` is what I needed. Thanks for your help everyone!
