### ISSUE TITLE
WebMock shouldn't raise exception when specifying headers as symbols

### ISSUE THREAD

**Issue by akestner** [bblimke/webmock#595]
As of Ruby `v2.3.0` it's acceptable to specify `Net::HTTP` headers as symbols (https://github.com/ruby/ruby/commit/1a98f56ae14724611fc8f7c220e470d27f6b57e4), but webmock currently raises `ArgumentError.new("Net:HTTP does not accept headers as symbols")` if you do.

This was introduced in #515, I'd propose wrapping that behavior with a check of `RUBY_VERSION`.

**Comment by bblimke** [comment]
@akestner good idea. do you fancy a pull request?

**Comment by akestner** [comment]
Had started on one, but couldn't get a couple of the dependencies to install (`eventmachine` and `unf_ext`).
