### ISSUE TITLE
WebMock removes "*-Authorization" header

### ISSUE THREAD

**Issue by sirn** [bblimke/webmock#599]
In one of web app I'm working on, I met with a situation where I'm require to pass `Authorization` and `X-Legacy-Authorization` within a single request (it is an app that do transform request for other components in the stack).

Once I start testing the app with WebMock, I found that any headers that contained "Authorization" string with its value starting with "Basic" are removed (in [net_http.rb#L290](https://github.com/bblimke/webmock/blob/1d9c9159fb9351577fe193af50b53a12f6e13577/lib/webmock/http_lib_adapters/net_http.rb#L290)) making both headers not inspectable.

I have read #591 and understand that the behavior is somewhat expected, but I think it would be nice if the `userinfo` rewriting a little bit less aggressive or if there is some sort of `:url`/`:header`/`:auto` flag to override this transformation.

I'm currently using:

* webmock 1.24.2
* rest-client 1.8.0

**Comment by bblimke** [comment]
Could you please verify that version 2.0.0.beta1 resolves this issue? Please see the changes https://github.com/bblimke/webmock/blob/2.0/CHANGELOG.md#200

**Comment by sirn** [comment]
@bblimke I can confirm that 2.0.0.beta1 solve this issue. Thanks!
