### ISSUE TITLE
Allowing URL isn't allowed when using OpenURI open method

### ISSUE THREAD

**Issue by gabrieljoelc** [bblimke/webmock#600]
I'm probably missing something, but why is webmock allowing a URI through `Net::HTTP` but not through `OpenURI` (using `webmock` 1.24.2)?
```ruby
include WebMock::API
google = 'https://www.google.com'
WebMock.disable_net_connect!(allow: google)
uri = URI.parse(google)
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri.request_uri)
#=> #<Net::HTTP::Get GET>
open(google)
# WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET https://www.google.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}

# You can stub this request with the following snippet:

#stub_request(:get, "https://www.google.com/").
#  with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-#Agent'=>'Ruby'}).
#  to_return(:status => 200, :body => "", :headers => {})

#============================================================
#from /Users/gabrieljoelc/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/webmock-1.24.2/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
```

**Comment by crazydog115** [comment]
It looks like the `allow` option of `disable_net_connect` doesn't support passing in the protocol.

Changing that line to
```ruby
WebMock.disable_net_connect!(allow: 'www.google.com')
```

causes your code to work.

**Comment by gabrieljoelc** [comment]
Oh you are right. Is it because the `OpenURI` method isn't correctly constructing a SSL request or something? Why would webmock see that `Net::HTTP` request as matching the allow and not the `OpenURI` one?

**Comment by gabrieljoelc** [comment]
Even with the protocol is removed weird things happen (related to SSL):
```ruby
WebMock.disable_net_connect!(allow: %r{github.com/bblimke/webmock})
uri = URI('https://github.com/bblimke/webmock')
open(uri)
#=> disallowed
Net::HTTP.get(uri)
#=> disallowed
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri.request_uri)
#=> allowed
```

**Comment by crazydog115** [comment]
So all of those requests work if you change the first line to
```ruby
WebMock.disable_net_connect!(allow: %r{github.com})
```
For some reason the `uri.request_uri` isn't working in the allow list. Not sure if that's a bug or not.

**Comment by gabrieljoelc** [comment]
> So all of those requests work if you change the first line to

Yea, I see that removing the path makes it work but I don't want to remove the path. Plus, the [readme](https://github.com/bblimke/webmock#external-requests-can-be-disabled-while-allowing-specific-requests) says that you should be able to use a regular expression including a path:

> ```ruby
> WebMock.disable_net_connect!(:allow => %r{ample.org/foo})
> 
> RestClient.get('www.example.org', '/foo/bar') # ===> Allowed
> RestClient.get('sample.org', '/foo')          # ===> Allowed
> RestClient.get('sample.org', '/bar')          # ===> Failure
> ```

> For some reason the uri.request_uri isn't working in the allow list

I'm not sure what you mean by that since using the `uri.request_uri` with the `Net::HTTP::Get.new(uri.request_uri)` is the only one that works when the path is included in the `allow`.

**Comment by gabrieljoelc** [comment]
this works ( :unamused: ):
```ruby
WebMock.disable_net_connect!(allow: lambda { |uri| uri.host == 'github.com' && uri.path == '/bblimke/webmock' })
uri = URI('https://github.com/bblimke/webmock')
open(uri)
#=> allowed!!!
Net::HTTP.get(uri)
#=> allowed!!!
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri.request_uri)
#=> allowed
```

**Comment by bblimke** [comment]
@gabrieljoelc in your examples `request = Net::HTTP::Get.new(uri.request_uri)` always works, because it doesn't make any network request. you are just constructing a request object and not making a call. It doesn't even touch WebMock.

I have added support for `allowed` option with scheme added.

Scheme was not supported.

**Comment by bblimke** [comment]
The regexp issue was a bug indeed. Thanks for reporting.

**Comment by gabrieljoelc** [comment]
> `request = Net::HTTP::Get.new(uri.request_uri)` always works, because it doesn't make any network request

@bblimke yea, i know. i think i just copied and pasted wrong in the comments 😊
