### ISSUE TITLE
RSpec - expect a_request - undefined with

### ISSUE THREAD

**Issue by dsandstrom** [bblimke/webmock#602]
RSpec 3.4
Webmock 1.24.2

When using something like your example:
```ruby
expect(a_request(:get, "www.example.com").with(:query => {"a" => ["b", "c"]})).
  to have_been_made
```
I get an error:
```
NoMethodError:
       undefined method `with' for #<RSpec::Expectations::ExpectationTarget:0x007fb8345d54c8>
```
However, using expect on the WebMock class works:
```
expect(WebMock).to have_requested(:get, "www.example.com").
  with(:query => {"a" => ["b", "c"]})
```

**Comment by bblimke** [comment]
@dsandstrom are you sure you have used exactly the provided snippet `expect(a_request(:get, "www.example.com").with(:query => {"a" => ["b", "c"]})).
  to have_been_made` and it gave you this error?

Based on the error message you provided I suspect you had `expect(a_request(:get, "www.example.com")).with`. Please note the double parenthesis before `with`.

There are many examples of this syntax in WebMock test suite and they all pass on RSpec 3.4.

If you still get this, please provide a failing code example, so I can reproduce it.

**Comment by dsandstrom** [comment]
Yeah, that was it.  I was cutting off `expect` too early.  Thanks for guidance.
