### ISSUE TITLE
RuntimeError: can't modify frozen String with v1.24.3+, Net::HTTP, and older Rubygems

### ISSUE THREAD

**Issue by cgriego** [bblimke/webmock#607]
Older versions of RubyGems raise `RuntimeError: can't modify frozen String` when a frozen string, like `RUBY_VERSION`, is passed to `Gem::Version.new`. v1.24.3 introduced code that does just that for dealing handling symbol headers with Net::HTTP. Can we workaround this and restore compatibility by duping `RUBY_VERSION` before passing it?

**Comment by bblimke** [comment]
Released as 1.24.5. Thanks!

**Comment by cgriego** [comment]
Thanks @bblimke for the quick turnaround, but unfortunately 1.24.5 still has the issue. Looks like the test code was changed but the runtime code is still passing the frozen RUBY_VERSION to Gem::Version so it's still giving older rubygems an issue.

**Comment by bblimke** [comment]
sorry for that. released again as 1.24.6

**Comment by cgriego** [comment]
Now it works. Thank you!
