### ISSUE TITLE
webmock 2.0.0 no longer intercepting http.rb requests

### ISSUE THREAD

**Issue by tarcieri** [bblimke/webmock#610]
After upgrading to webmock 2.0.0, it ceases to intercept HTTP requests from [http.rb](https://github.com/httprb/http).

Downgrading to 1.24.2 fixes the problem.

/cc @ixti

**Comment by ixti** [comment]
Will take a look today-tomorrow

**Comment by bblimke** [comment]
@tarcieri have you checked the 2.0.0 CHANGELOG.md?

**Comment by tarcieri** [comment]
@bblimke I have now. I don't see any obvious culprits.

**Comment by bblimke** [comment]
@tarcieri ok. I guess you are using webmock in specs, therefore it's still enabled by default right?

**Comment by tarcieri** [comment]
In the particular case in question, I'm using it vicariously via VCR, so perhaps there's some sort of odd interaction there (I explicitly configure VCR to use webmock)

Anything to look out for in a webmock 1.x -> 2.x transition there?

**Comment by bblimke** [comment]
VCR is not compatible with webmock 2.0 yet. https://github.com/vcr/vcr/issues/570

In particular VCR does not enable WebMock (which is now disabled by default)

**Comment by bblimke** [comment]
nothing to do with http.rb

**Comment by tarcieri** [comment]
alrighty then

**Comment by ixti** [comment]
:D
