### ISSUE TITLE
Webmock 2.0 does not mock em-http-request connections

### ISSUE THREAD

**Issue by 304** [bblimke/webmock#614]
I recently updated webmock version from `1.24.3` to `2.0` and found out that specs stopped working for me. After some investigation I noticed that webmock makes **real** http requests instead of mocking them. 

I've checked the difference between two version and I found that `require 'em-http-request'` was removed in [`lib/webmock/http_lib_adapters/em_http_request_adapter.rb`](https://github.com/bblimke/webmock/compare/v1.24.6...v2.0.0#diff-7621f71ad444d460f3fa632b855cc4e3L1).

``` diff
-begin
-  require 'em-http-request'
-rescue LoadError
-  # em-http-request not found
-end
```

Because of that, the code that should be initialised in order to catch these kind of requests is not triggered anymore. If I require `em-http-request` before `webmock/rspec` in my `spec_helper` then it fixes the issue.

Can you please tell me was it an intentional decision to remove `require 'em-http-request'` or it is a bug?
Thank you!

**Comment by bblimke** [comment]
That's a bug. Thanks for reporting. Fixed and released as 2.0.1

**Comment by 304** [comment]
Great job! Thank you! 👍

**Comment by thejamespinto** [comment]
Confirming this after upgrading to 2.0

if my output helps,
Thanks for maintaining this gem guys!


```
    em-http-request (0.2.11)
      addressable (>= 2.0.0)
      eventmachine (>= 0.12.9)
    eventmachine (1.2.0.1)
    webmock (2.0.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
```


```
/Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:14:in `<class:EmHttpRequestAdapter>': uninitialized constant EventMachine::HttpConnection (NameError)
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:10:in `<module:HttpLibAdapters>'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:9:in `<module:WebMock>'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/http_lib_adapters/em_http_request_adapter.rb:8:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock.rb:49:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock.rb:49:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/minitest.rb:11:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.2/gems/webmock-2.0.1/lib/webmock/minitest.rb:11:in `<top (required)>'
```
