### ISSUE TITLE
Bearer authorisation not working in webmock 2.x but worked in 1.x

### ISSUE THREAD

**Issue by TTransmit** [bblimke/webmock#617]
The following line of code successfully stubbed requests in 1.x but isn't working in 2.x. 

    stub_request(:get, "https://www.example.com/example-endpoint").with({headers: {'Authorization'=>"Bearer #{oauth_token}"}}).to_return(:body => mock_response)

The Bearer Authorization header is being overwritten with a 'Basic xxxxx' Authorization header. 

Commenting out lines 183-185 in em_http_request_adapter.rb makes the tests work with web mock 2.0.1

        # if headers['authorization']
        #   headers['Authorization'] = WebMock::Util::Headers.basic_auth_header(headers.delete('authorization'))
        # end

In the 2.0.0 changelog, it suggests writing such a request as 

    stub_request(:get, "www.example.com").
      with(headers: 'Authorization' => "Basic #{ Base64.encode64('user:pass').chomp}")

which Ruby cannot interpret. 

The change seems to have been made in this commit: 
https://github.com/bblimke/webmock/commit/edfafd2b821dd1f49c1e5d774907b44aab049e8f

**Comment by bblimke** [comment]
Fixed in version 2.0.2

**Comment by TTransmit** [comment]
Thanks for fixing this and thanks for creating this excellent library. I can confirm that stub_request now works as expected with Bearer authorisation headers.

**Comment by bblimke** [comment]
cheers! :)
