### ISSUE TITLE
Curb do not trigger on_debug call back

### ISSUE THREAD

**Issue by ravenesi** [bblimke/webmock#621]
Hi,
web mock curb implementation do not trigger on_debug callback ... because of that i did this work in initializers... 

spec/support/webmock_curb_fix.rb

``` ruby
# frozen_string_literal: true
if defined?(Curl) && defined?(WebMock)
  module Curl
    WebMockCurlEasy.class_eval do
      def on_debug
        yield if block_given?
      end
    end
  end
end
```

**Comment by bblimke** [comment]
@ravenesi any idea why it doesn't work with webmock?

**Comment by ravenesi** [comment]
@bblimke indeed our WebMock implementation do not implement proper on_debug callback other callbacks are there i can create PR is is it needed :)

**Comment by bblimke** [comment]
a PR would be very welcome :)
