### ISSUE TITLE
API for getting current request?

### ISSUE THREAD

**Issue by bootstraponline** [bblimke/webmock#624]
I'm persisting requests to disk and then using webmock to make sure the requests match the recorded versions.

```ruby
def current_request
  # WebMock::RequestSignature
  WebMock::RequestRegistry.instance.requested_signatures.hash.keys.first
end
```

Is there a better way to get the current request? The use case is `::YAML.dump(current_request)`

**Comment by bblimke** [comment]
You can use the request callback and store the current request on your own.

https://github.com/bblimke/webmock#request-callbacks

**Comment by bootstraponline** [comment]
```
WebMock.after_request do |request, response|
  SpecHelper.current_request = request
end
```

Thanks. That worked.

**Comment by keithbro** [comment]
👍
