### ISSUE TITLE
Third-Party curb ?? Why ?

### ISSUE THREAD

**Issue by lucasgomide** [bblimke/webmock#636]
On branch master(https://github.com/taf2/curb) the method `Curl.patch` executes `post_body` if body is present.

Our Gemfile indicate a third-party gem for `curb` (https://github.com/pavel-jurasek-bcgdv-com/curb). In this repo the method `Curl.patch` executes `put_data` if body is present. 

My question is, why the webmock uses a third-party gem ???

**Comment by bblimke** [comment]
@lucasgomide thanks for raising that. I don't know how I haven't spotted that.

To be honest, WebMock should not even rely on curb from taf2/curb master,
only on released versions from rubygems.

**Comment by lucasgomide** [comment]
@bblimke I agree. I'll take it.

**Comment by bblimke** [comment]
cheers :)
