### ISSUE TITLE
Web mock disable_net_connect! not working

### ISSUE THREAD

**Issue by vikramjadon921995** [bblimke/webmock#650]
In my spec_helper.rb file, when i write the code below and run specs, http requests to 'localhost' are blocked by webmock,  but it should ideally allow http requests to both localhost and codeclimate.
```
WebMock.disable_net_connect!(allow_localhost: true)
WebMock.disable_net_connect!(allow: [/codeclimate.com/])
```
The http requests to 'localhost' are not blocked if i remove the second line to allow http requests to 'codeclimate.com'.

**Comment by bblimke** [comment]
calling WebMock.disable_net_connect! overwrites the previous settings. 

Please add both settings to the same call `WebMock.disable_net_connect!(allow_localhost: true, allow: [/codeclimate.com/])`

**Comment by vikramjadon921995** [comment]
Ok, so it must be overwriting allow_localhost settings. Thanks.
