### ISSUE TITLE
Excon adapter omits the response reason_phrase

### ISSUE THREAD

**Issue by SpComb** [bblimke/webmock#653]
Testing the application HTTP client's error handling by mocking an HTTP 500 response and expecting an exception containing the "Internal Server Error" reason phrase does not work. It looks like the resulting `Excon::Response` does not actually include the status phrase:

`#<Excon::Response:0x0000000226e628 @data={:body=>"", :headers=>{}, :status=>500, :remote_ip=>"127.0.0.1"}, @body="", @headers={}, @status=500, @remote_ip="127.0.0.1", @local_port=nil, @local_address=nil>`

Looks like the [`WebMock::HttpLibAdapters::ExconAdapter#real_response`](https://github.com/bblimke/webmock/blob/v2.1.0/lib/webmock/http_lib_adapters/excon_adapter.rb#L127) function omits that part of the mocked response status?

``` ruby
    {
            body: mock.body,
            status: mock.status[0].to_i,
            headers: mock.headers || {}
    }
```

Example:

``` ruby

  describe '#request' do
    subject do
      Kontena::Client.new('http://localhost', master.token)
    end

    context "with a 500 response" do
      before :each do
        WebMock.stub_request(:any, 'http://localhost/v1/test').to_return(
          status: [500, "Internal Server Error"],
        )
      end

      it "raises StandardError with the ISE message" do
        expect{subject.get('test')}.to raise_error(Kontena::Errors::StandardError, /Internal Server Error/)
      end
    end
  end
```

```
  1) Kontena::Client#request with a 500 response raises StandardError with the ISE message
     Failure/Error: expect{subject.get('test')}.to raise_error(Kontena::Errors::StandardError, /Internal Server Error/)

       expected Kontena::Errors::StandardError with message matching /Internal Server Error/, got #<Kontena::Errors::StandardError: Kontena::Errors::StandardError> with backtrace:
```

**Comment by bblimke** [comment]
@SpComb thanks for reporting.

Fixed and released as version 2.1.1
