### ISSUE TITLE
stub ignores hash_including

### ISSUE THREAD

**Issue by lubekpl** [bblimke/webmock#654]
Hi!

I'm trying to stub a request using `hash_including`. The request in question has several parameters, one of them is a random generated number which I simply can't generate beforehand therefore I'm trying with `hash_including`.

While trying to use the snippet
```
stub_request(:post, "http://api.example.com/").
            with(body: hash_including('method' => 'get_contacts')).
            to_return(status: 200, body: "", headers: {})
```

I receive this NetConnectNotAllowedError: 
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST http://api.example.com/ with body '{"id":"1477046151-370617403-0","method":"get_contacts","params":["73eeac3fa1a0ce48f381ca1e6d71f077",{"email":{"EQUALS":"test@example.com"}}]}' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:

stub_request(:post, "http://api.example.com/").
  with(:body => "{\"id\":\"1477046151-370617403-0\",\"method\":\"get_contacts\",\"params\":[\"73eeac3fa1a0ce48f381ca1e6d71f077\",{\"email\":{\"EQUALS\":\"test@example.com\"}}]}",
       :headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
  to_return(:status => 200, :body => "", :headers => {})

registered request stubs:

stub_request(:post, "http://api.example.com/").
  with(:body => hash_including({"method"=>"get_contacts"}))
```

I tried using `hash_including` with different keys (e.g. params key), tried string keys, tried switching `body` to `query` in the stub, tried hash rockets.

Anybody have a clue why would `hash_including` not work for this stub?

**Comment by bblimke** [comment]
Your request doesn't have Content-Type header specified, therefore WebMock doesn't know how to represent the the request body as a hash and then match it to the hash_including matcher.

Please add Content-Type: 'application/json' header to the request.

**Comment by lubekpl** [comment]
That's what you get for running an old gem! Thank's a lot, don't know how I've missed it!
