### ISSUE TITLE
Stubbing is not working

### ISSUE THREAD

**Issue by magicalbanana** [bblimke/webmock#658]
I am trying to stub this

``` ruby
      it "skips routing number and performs the job" do
        WebMock.allow_net_connect!
        WebMock.stub_request(:any, '/www.frbservices.org\*/').to_return(
          body: "011000015O0110000150122415000000000FEDERAL RESERVE BANK                1000 PEACHTREE ST N.E.              ATLANTA             GA303094470877372245711"
        )
        described_class.new.perform
        WebMock.disable_net_connect!
      end
```

But the body being returned is still from this url, https://www.frbservices.org/EPaymentsDirectory/FedACHdir.txt

Can anyone help me with this? I am using RestClient when making the actual request.

**Comment by bblimke** [comment]
@magicalbanana I suggest stackoverflow. You will probably get answers earlier. Github issues are for issues with webmock, not with own code.

First, you probably want to use a regexp, not a string `/www.frbservices.org\*/` and not  `'/www.frbservices.org\*/'`

Second, the regexp is incorrect. You probably want ` '/www.frbservices.org\//'`
