### ISSUE TITLE
stub_request is "forgetting" the to_return portion of the stub

### ISSUE THREAD

**Issue by tgmerritt** [bblimke/webmock#661]
Please check the stackoverflow issue here:

https://stackoverflow.com/questions/40688496/stub-request-method-loses-the-to-return-portion

I'm not good enough to get you an entirely separate app with just this test - you can see what rspec tells me to stub, if you stub it out, then run a spec, it appears to forget about the "and_return" portion of the stub. Then it fails for obvious reasons. I can't see what I'm doing wrong - I've copied / pasted the message directly from the terminal that rspec suggests.

**Comment by bblimke** [comment]
@tgmerritt I have replied on stackoverflow.
