### ISSUE TITLE
Please don't pull published gem versions

### ISSUE THREAD

**Issue by amilligan** [bblimke/webmock#666]
Steps to reproduce:
1. You published 2.3.0
1. We updated our bundle to 2.3.0
1. You pulled 2.3.0
1. Death from above

**Comment by bblimke** [comment]
@amilligan sorry for that.

2.3.0 was a invalid release, thats why I have yanked it and released 2.3.1

Any idea how this could have been done better? I don't want invalid releases to be available.

It looks like yanking gem these days removes it completely from rubygems.

**Comment by istana** [comment]
I think you can keep it public on rubygems, because the gem follows semantic versioning, so `bundle update` will use the latest minor release.
