### ISSUE TITLE
rails 5 rspec 3.5 stub_request regex where url params exists and does not exist

### ISSUE THREAD

**Issue by chrishough** [bblimke/webmock#676]
With the help of fellow engineers we have been battling this issue http://stackoverflow.com/questions/41405477/rails-5-rspec-3-5-stub-request-regex-where-url-params-exists-and-does-not-exist and was wondering if anyone had ideas.

**Comment by bblimke** [comment]
@chrishough shall I assume based on the following answer http://stackoverflow.com/a/41412179/18715 that the issue is now resolved?

**Comment by chrishough** [comment]
As it turns out the way the gem was working it was taking the url params and transitioning them to post body params. Once adjusted it was working. Thank you.
