### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by voxik** [bblimke/webmock#677]
Curb was always licensed under Ruby license as far as I can say. At least the LICENSE file looks to be Ruby license and Ruby license is also mentioned in plenty of file headers as well as it is referenced in README. But the .gemspec file says (since #251) it is MIT. Could you please fix the license in the .gemspec file, since it seems to be the only place where the MIT is mentioned?

**Comment by bblimke** [comment]
@voxik Could you please explain why webmock license would have to be changed? What does Curb license have to do with Webmock license? Webmock is MIT. It's not being shipped with Curb code inside. Curb is just a development dependency, therefore Curb's license doesn't affect webmock.

**Comment by voxik** [comment]
Ah, that was good report but on the wrong place. Going to report this against Curb. Sorry for the noise 😊

**Comment by bblimke** [comment]
No problem :)
