### ISSUE TITLE
Is there any special reason to use .* in regex?

### ISSUE THREAD

**Issue by georgeu2000** [bblimke/webmock#684]
From the Readme:

`stub_request(:any, /.*example.*/)`

I \*believe* this is the same as `stub_request(:any, /example/)`

Is that correct? If so, can we remove .* from the docs?

**Comment by bblimke** [comment]
@georgeu2000 good point! That should make the README cleaner.

Do you fancy submitting a pull request?

**Comment by georgeu2000** [comment]
It would be my pleasure.

**Comment by jfharden** [comment]
I think this issue can be closed now?

**Comment by bblimke** [comment]
@jfharden 👍
