### ISSUE TITLE
Suggested stub body should be valid JSON when request header contains 'Accept'=>'application/json'

### ISSUE THREAD

**Issue by redbar0n** [bblimke/webmock#688]
When the request has a `'Accept'=>'application/json'` header set, then Webmock suggests a `:body => ""`:

    You can stub this request with the following snippet:

    stub_request(:post, <some_url>).
          with(:body => <some_body>,
               :headers => {'Accept'=>'application/json' }).
          to_return(:status => 200, :body => "", :headers => {})

but doing a `JSON.parse(response.body)` will give an:

`JSON::ParserError: A JSON text must at least contain two octets!`

What Webmock should suggest instead is simply a `:body => "{}"`

    You can stub this request with the following snippet:

    stub_request(:post, <some_url>).
          with(:body => <some_body>,
               :headers => {'Accept'=>'application/json' }).
          to_return(:status => 200, :body => "{}", :headers => {})

Since that would be parseable by Ruby's JSON library:
```
> irb
>> JSON.parse("")
JSON::ParserError: 743: unexpected token at ''
	from /Users/Magne/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from /Users/Magne/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from (irb):3
	from /Users/Magne/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
>> JSON.parse("{}")
=> {}
```

**Comment by bblimke** [comment]
@edbar0n I guess that very much depends on what the mythical server would really respond with.
That server could take into account Accept headers or ignore them.

`to_return(:status => 200, :body => "", :headers => {})` is just a simplest response,
to give people idea how to declare a stub, but implementing the actual response
is something WebMock can't make any assumptions about.
It's a programmers job to declare the specific response.

**Comment by redbar0n** [comment]
I realize that the Webmock suggestion is just a starting point for implementing the actual response. But doesn't it make sense that the starting point which Webmock suggests should be a good starting point, i.e. something that would work?

It's an assumption either way: That the server would ignore the Accept header (like it currently does), or that it takes it into account (responding with JSON if the client asks for JSON). I'd argue that it would be more common to take it into account, and that it would give a better starting point for programmers. Who would implement a request that asks for JSON, and not initially expect to actually receive JSON back in the response?

Besides: In this simplest response, the stub already makes assumptions about what the server does, by returning status 200 and a hash for the headers. To be perfectly agnostic, the stub ought to have suggested an empty string for all the return fields, really (or not respond with anything at all, since it's not certain that the server has been implemented to actually respond). Not that I think that would have been better than giving a good starting point to the programmer to work from.

**Comment by redbar0n** [comment]
I'd be happy to implement the fix myself and submit a pull request, if that carries any weight. The decision about what to do with this is entirely up to you, of course.

**Comment by bblimke** [comment]
@redbar0n ok, I'm convinced. Thank you :)

I'd be happy to accept a pull request.

**Comment by redbar0n** [comment]
Great. :) I implemented the fix and added a test case for it. It was a very small change.

**Comment by bblimke** [comment]
Thank you!
