### ISSUE TITLE
Documentation: Stubbing a request with any query

### ISSUE THREAD

**Issue by joallard** [bblimke/webmock#693]
I haven't found how to do this in the examples, so I'm filing this as a documentation issue.

How do I stub a request to a particular URL ("example.com/a/b"), not caring about the query string?

If I only stub the URL, it doesn't hit the stub.

**Comment by bblimke** [comment]
How about regular expression?
https://github.com/bblimke/webmock#matching-uris-using-regular-expressions

**Comment by joallard** [comment]
That's how I worked around it. I thought there'd be a first class way to do this, okay then

**Comment by bblimke** [comment]
@joallard alternatively `.with(query: hash_including({})` but it's also a workaround.

WebMock treats query as part of the url, therefore if it's empty, it expects it to be empty.
Perhaps that should be changed in the future.

**Comment by joallard** [comment]
Thanks @bblimke !
