### ISSUE TITLE
Port 80 connections are handled incorrectly

### ISSUE THREAD

**Issue by pstengel** [bblimke/webmock#696]
Consider the following code and spec:

```ruby
require "net/http"

require "rspec"
require "webmock/rspec"

class BugReport
  def self.do_request(addr)
    Net::HTTP.start(addr, 80) { |http| http.request(Net::HTTP::Get.new("/")) }
  end
end

RSpec.describe BugReport do
  describe ".do_request" do
    before { stub_request(:any, "example.com:81").and_return(status: 200) }

    it "should fail" do
      described_class.do_request("example.com:81")
      expect(WebMock).to have_requested(:any, "example.com:81")
    end
  end
end
```

I would expect the test to fail given that we explicitly are telling `Net::HTTP.start` to connect on port 80, making the hostname we pass to `Net::HTTP.start` invalid. However, the test succeeds:

```
BugReport
  .do_request
    should fail

Finished in 0.00264 seconds (files took 0.26929 seconds to load)
1 example, 0 failures
```

If I issue the request directly via `Net::HTTP` without mocking the request, it fails as you would expect:

```
irb(main):002:0> Net::HTTP.start("example.com:81", 80) { Net::HTTP::Get.new("/") }
SocketError: Failed to open TCP connection to example.com:81:80 (getaddrinfo: nodename nor servname provided, or not known)
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/pstengel/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from (irb):2
	from /Users/pstengel/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
```

Since `:80` is not added to URIs as a result of it being the default port for the protocol, WebMock is incorrectly comparing the contents of the hostname to the stubbed URL and passing the request. If I change `Net::HTTP.start` to connect on port 81 instead of 80 in the code snippet at the beginning of this report, the request fails as you would expect and is fixed by specifying the corrected hostname without the port.

**Comment by bblimke** [comment]
You should decide whether you want to connect to port 80 or 81.

Where is ` Net::HTTP.start("example.com:81", 80)` supposed to connect? Port 80 or 81.

Your example is broken since you pass url with host and port and then you pass port 81 as well.

If you have a look at the error, it's not the error from webmock but from Net::HTTP which complains that there is no such url as `example.com:81:80`

**Comment by pstengel** [comment]
Yeah, I debated on whether or not to even report this because I had the same line of thinking you did. On one hand, the use of `Net::HTTP.start` in the code snippet I provided is just wrong. On the other hand, WebMock doesn't detect this and `Net::HTTP.start` has different behavior: WebMock reports the code works fine, direct use of `Net::HTTP.start` shows it does not.

I would expect the test to fail simply because the actual usage fails. I agree that the usage of `Net::HTTP.start` is incorrect, but I also think WebMock should be able to detect this specific case and also fail.

**Comment by bblimke** [comment]
@pstengel if you fancy to provide a test covered pull request to cover that invalid scenario that nobody is ever going to use, feel free.

I'm sure there are plenty of incorrect usages of Net::HTTP or other ruby http client libs that Webmock doesn't handle either, but it's not a problem for anybody.
