### ISSUE TITLE
Is webmock support mechanize now?

### ISSUE THREAD

**Issue by tsaohucn** [bblimke/webmock#699]
I use rspec and webmock to stub the HTTP request, but no matter how can I stub, it alaways show error message like that, I use google try to reserach some answaers and it seems like webmock doesn't support mechanize, I am not really sure so that I commit the issue to check is it a bug or really no support on mechanize? If no support on mechanize, will support in the future?

    Failure/Error: @page ||= mechanize.get(valid_url(url))

     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://tsaohucn.wordpress.com/ with headers {'Accept'=>'*/*', 'Accept-Charset'=>'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Accept-Encoding'=>'gzip,deflate,identity', 'Accept-Language'=>'en-us,en;q=0.5', 'Connection'=>'keep-alive', 'Host'=>'tsaohucn.wordpress.com', 'Keep-Alive'=>'300', 'User-Agent'=>'Mechanize/2.7.5 Ruby/2.3.1p112 (http://github.com/sparklemotion/mechanize/)'}

       You can stub this request with the following snippet:

       stub_request(:get, "https://tsaohucn.wordpress.com/").
         with(headers: {'Accept'=>'*/*', 'Accept-Charset'=>'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Accept-Encoding'=>'gzip,deflate,identity', 'Accept-Language'=>'en-us,en;q=0.5', 'Connection'=>'keep-alive', 'Host'=>'tsaohucn.wordpress.com', 'Keep-Alive'=>'300', 'User-Agent'=>'Mechanize/2.7.5 Ruby/2.3.1p112 (http://github.com/sparklemotion/mechanize/)'}).
         to_return(status: 200, body: "", headers: {})

       registered request stubs:

       stub_request(:get, "https://tsaohucn.wordpress.com/").
         with(headers: {'Accept'=>'*/*', 'User-Agent'=>'Ruby'})
       stub_request(:any, "http://api.stripe.com/")
       stub_request(:any, "/api.stripe.com/")

**Comment by bblimke** [comment]
User agent header doesnt match your stub
