### ISSUE TITLE
Add support for detecting if WebMock is enabled

### ISSUE THREAD

**Issue by redconfetti** [bblimke/webmock#701]
# Feature Request

I'm encountering a use case where we would like to check if WebMock is enabled or not.

``` ruby
> WebMock.enabled?
=> false
> WebMock.enable!
> WebMock.enabled?
=> true
> WebMock.disable!
> WebMock.enabled?
=> false
```

## Use Case

The application I'm working on raises exceptions when HTTP 400+ response is received, and depending on the circumstance the exception is caught and logged with a stack trace.

When we're using WebMock, these stack traces are not needed in our logs. They're really cluttering up the TravisCI logs unnecessarily. We'd like to exclude the error or stack traces from our logs when WebMock is being used. Support for `WebMock.enabled?` would really help with this.

## Approach

I'm thinking of making a pull request for this myself. A simple class variable boolean that is modified in [WebMock.enabled!](https://github.com/bblimke/webmock/blob/e3d0cd1c/lib/webmock/webmock.rb#L36,L42) and WebMock.disabled! is all that's needed.

```
@@enabled = true
```

**Comment by bblimke** [comment]
Thanks for a well defined issue.

It all makes sense except the fact WebMock can be enabled only for some http clients.
https://github.com/bblimke/webmock#disabling-and-enabling-webmock-or-only-some-http-client-adapters

Any ideas?

**Comment by redconfetti** [comment]
Yes. You have a point. 

I was also just thinking that some requests using the same adapter may be mocked, while others are not. It sounds like my request is too global to be practical for most others using this library.

Someone could use `WebMock::StubRegistry.instance.registered_request?` to check if the request is being stubbed. Even then, there isn't a true correlation between the raised exception and the request response.

🤔
