### ISSUE TITLE
Conflict with Rails 5.1, Webpacker, and webpack-dev-server

### ISSUE THREAD

**Issue by brycesenz** [bblimke/webmock#716]
I was playing around with a new Rails 5.1 project that was using the following:

- Ruby 2.4.1
- Rails 5.1.4
- Webpacker 3.0.1
- Webmock 1.24.6 (Older version, I know)

I noticed that in my Gemfile, if I had Webmock in the `:test` and `:development` groups, then in development it broke the functionality of the `bin/webpack-dev-server`.

My fix was simply to make sure that Webmock was restricted to the `:test` environment.  I think that this behavior is correct, strictly speaking, but wanted to leave a record of the problem for the benefit of others.

**Comment by bblimke** [comment]
@brycesenz since version 2.0, webmock is not enabled by default, therefore this issue is not relevant anymore.

**Comment by brycesenz** [comment]
@bblimke - Perfect!  I thought the older version might have been the culprit, but wasn't sure.  In any case, I just wanted to leave a note in case someone else runs into a similar issue.

**Comment by argent-smith** [comment]
@bblimke I need both (webpacker & webmock) in development. Could there be any workaround?

**Comment by brycesenz** [comment]
@argent-smith - it sounds (based on the comment) that there should be no conflict if you're using the up to date version of this gem.  I just ran into an issue because I was using the older version.

**Comment by bblimke** [comment]
@brycesenz thanks for responding.

@argent-smith this is a different issue than https://github.com/bblimke/webmock/issues/374#issuecomment-414437255
