### ISSUE TITLE
Does not play well with iframes

### ISSUE THREAD

**Issue by stevenspiel** [bblimke/webmock#719]
I have an iframe on a page that I'm trying to stub, but the iframe keeps loading (regardless of the `src`). Even if I `stub_request`, it still loads the website within the iframe. Webmock is working fine in every other context I've used it, but it seems to be ignoring iframes. Is that by design?

**Comment by bblimke** [comment]
@stevenspiel I'm not sure I understand what you mean by "page that I'm trying to stub". 
Webmock is only capable of intercepting http requests made by Ruby http clients.

**Comment by stevenspiel** [comment]
Ok, thank you!

**Comment by stevenspiel** [comment]
For anyone interested, I ended up solving my issue using [puffing-billy](https://github.com/oesmith/puffing-billy)

Billy and Webmock don't work together, but I was able to keep all of my webmock stubs by [doing this](https://github.com/oesmith/puffing-billy/issues/44#issuecomment-120055479).

**Comment by vfonic** [comment]
I've hit the same issue.

Basically, any `<script>`, `<link>`, `<img>`, etc. tag load successfully through webmock stub. But `<iframe>` loads the actual website.

I have this code and it's not working:

```html
<script src="http://google.com"></script> <!-- caught by webmock stub -->
<iframe src="http://google.com"></iframe> <!-- loads actual google.com -->
```

If something is unclear, I can make a rails app with repro steps.

Should this issue be reopened?

**Comment by bblimke** [comment]
@vfonic WebMock does not intercept the requests made by the browser to external urls.
WebMock only intercepts requests made by Ruby apps. 

Unless it's some Ruby app that parses that html and makes the requests, it's not going to intercept these request.

Is the script really loaded from google.com as I don't know why it would be intercepted by WebMock otherwise?

**Comment by vfonic** [comment]
You're right, both of the above are making network requests.

I'll see what I can do to avoid this in some other way.

**Comment by bblimke** [comment]
@vfonic how do you run your tests? what browser loads the page and makes the requests? is that with capybara and selenium?

**Comment by vfonic** [comment]
@bblimke yes, I use capybara and selenium. These are run through rspec in a rails app.

**Comment by bblimke** [comment]
@vfonic then as per @stevenspiel suggestion, please use something like puffing-billy.
WebMock doesn't have access to the web browser used by selenium.
