### ISSUE TITLE
Net::HTTP adapter converts empty response body to nil response body

### ISSUE THREAD

**Issue by jeffcharles** [bblimke/webmock#722]
When I provide a stub like:

```
stub_request(:get, 'https://foo.com')
  .to_return(status: 200, body: '')
```

I expect that `response.body` will be an empty string. Instead `response.body` is `nil`. There are many APIs where an empty response body but not a nil one are returned.

E.g.,

```
require 'net/http'
https = ::Net::HTTP.new('httpbin.org', 443)
https.use_ssl = true
request = ::Net::HTTP::Get.new('/status/200')
https.request(request).body
=> ""
```

It looks like`webmock/lib/webmock/http_lib_adapters/net_http.rb` on line 157 has:

```
body = nil if body.to_s == ''
```

which I suspect is where the unwanted conversion is happening.

**Comment by bblimke** [comment]
Thank you for reporting!

That behaviour should only be the case for 204 responses.

Fixed and released as 3.1.0
