### ISSUE TITLE
Multiple responses for repeated requests not acting as expected

### ISSUE THREAD

**Issue by pedrocaseiro** [bblimke/webmock#728]
If I create a request stub as follows

```
stub_request(:post, /query/)
    .to_return(
        { body: DataFixtures.load('fixture1') },
        { body: DataFixtures.load('fixture2') }
    )
```

And then make two calls that match the /query/ regex, why is my first call getting the `fixture2` as a return and not the `fixture1`?

**Comment by lefterisnik** [comment]
@pedrocaseiro I have the same issue. Have you solved your problem?
