### ISSUE TITLE
Add blocky assert_request helper method to encourage verified stubbing

### ISSUE THREAD

**Issue by grosser** [bblimke/webmock#737]
Atm verified stubbing is a bit ugly:

```Ruby
request = stub_request(foo)
do stuff
assert_requested request, times: 2
```

I'd propose adding a block helper to make this nicer:

```Ruby
assert_request(foo, times: 2) { do stuff } 
```

Implementation and usage can be seen here https://github.com/zendesk/samson/pull/2458

... ideally it should also de-register the stubs when the block is finished

**Comment by oliakremmyda** [comment]
Hi @grosser,

Do you need any further support on this or we can close this issue?
