### ISSUE TITLE
Net::HTTP.socket_type is BufferedIO and needs an argument

### ISSUE THREAD

**Issue by mikker** [bblimke/webmock#744]
Getting some errors in JRuby when at this line:
https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/net_http.rb#L80

Seems to me `Net::HTTP.socket_type` returns a `Net::BufferedIO`[1] and those need at least one argument[2].

1: http://www.rubydoc.info/stdlib/net/Net/HTTP#socket_type-class_method
2: http://www.rubydoc.info/stdlib/net/Net/BufferedIO#initialize-instance_method

**Comment by bblimke** [comment]
@mikker are you able to extract a failing spec or a simple snippet of code to reproduce the issue?

**Comment by mikker** [comment]
I'll try!

**Comment by mikker** [comment]
I couldn't reproduce outside the project I came upon this. And I think the error there wasn't directly related to WebMock. The investigation above might still be true though. Maybe no one ever hits that path anymore? Maybe we'll never know.
