### ISSUE TITLE
Cannot stub my request properly when it contains $ inside my query

### ISSUE THREAD

**Issue by rapides** [bblimke/webmock#749]
Code:
![image](https://user-images.githubusercontent.com/2733755/37337382-66e1b6c8-26b4-11e8-9453-008ddca6b31c.png)

Console:
![image](https://user-images.githubusercontent.com/2733755/37337527-dca252b4-26b4-11e8-823e-81f3410f64f1.png)

Is it a bug or did I do something wrong?

**Comment by bblimke** [comment]
Can you please provide a complete sample code or a spec that demonstrates the issue?

**Comment by rapides** [comment]
@bblimke sure, here you go:

my api wrapper:
![image](https://user-images.githubusercontent.com/2733755/37384229-e1c9fb9a-274d-11e8-8f31-ab411d96048f.png)

and its tests:

![image](https://user-images.githubusercontent.com/2733755/37384216-d3548378-274d-11e8-9b13-467b95183fa2.png)

**Comment by bblimke** [comment]
@rapides I meant a simple text snippet that I can just run locally to reproduce the issue.

**Comment by rapides** [comment]
```
stub_request(:get, 'http://google.com')
  .with(query: { query: { eventType: { '$in': ['Investment'] } } })
  .to_return(body: 'My message', status: 200)

# It doesn't work
HTTParty.get('http://google.com?query[eventType][$in][]=Investment')
```

**Comment by rapides** [comment]
@bblimke any update?

**Comment by rapides** [comment]
@bblimke please have a look once again on this issue because we stuck here. I'm not sure but it seems that I found a bug.

**Comment by bblimke** [comment]
@rapides this is most likely a bug. I'll have a look at it when I find some time.

For the time being I suggest stubbing the request with a string url with query.
`stub_request(:get, 'http://google.com?query[eventType][$in][]=Investment')`

**Comment by rapides** [comment]
Thanks for your time, I appreciate it! Let me know when ready 👍

**Comment by bblimke** [comment]
@rapides this is now fixed in master.

**Comment by oliakremmyda** [comment]
Corrected in https://github.com/bblimke/webmock/commit/277da1475921fade5d5c536b9a7de1f55f7dfb3a
