### ISSUE TITLE
Customize which stuff to mock

### ISSUE THREAD

**Issue by phuong-nguyen** [bblimke/webmock#75]
I want to mock HTTP::Net, but do not want to mock Curb, since I want to use Curb for Capybara Selenium and Webmock seems to clash with Capybara Selenium at some times. Currently I cannot find a way to do it with Webmock

**Comment by mzedeler** [comment]
I think this isn't a very elegant solution because the choice of HTTP driver is an implementation detail. I'd prefer if WebMock could allow requests with the Selenium user agent header in stead.
