### ISSUE TITLE
Patron PATCH stub doesn't detect the body

### ISSUE THREAD

**Issue by iMacTia** [bblimke/webmock#750]
Hello, while updating our tests in Faraday, I noticed a strange behaviour from Patron.
It seems like when providing a body (data) to a patch call, the body gets discarded, hence WebMock raises an exception.
The some doesn't happen, however, for other methods including put.

At first I though Patron wasn't working properly, so I opened an [issue](https://github.com/toland/patron/issues/163#issuecomment-373216356) there, but it turned out Patron is indeed sending the body correctly. So I suspect it's WebMock not detecting it properly.
Below a script to reproduce the issue (plus a working script with put method).

Patron version: 0.12.1
WebMock version: 3.3.0

Script to reproduce:
```ruby
require 'patron'
require 'webmock'

include WebMock::API

WebMock.enable!

stub_request(:patch, "http://example.com/")
  .with(body: {"name"=>"zack"})

session = Patron::Session.new
session.patch('http://example.com', "name=zack")
# => Raises WebMock::NetConnectNotAllowedError
```

The same doesn't happen, however, if we use `:put` instead of `:patch`.

```ruby
require 'patron'
require 'webmock'

include WebMock::API

WebMock.enable!

stub_request(:put, "http://example.com/")
  .with(body: {"name"=>"zack"})

session = Patron::Session.new
session.put('http://example.com', "name=zack")
# No exception raised
```

**Comment by bblimke** [comment]
@iMacTia thanks for reporting. This is now fixed in master.

**Comment by iMacTia** [comment]
Thanks @bblimke! Glad to know this was addressed!
I'll give it a try and feedback here as soon as possible.
Will also close the issue on successful feedback

**Comment by iMacTia** [comment]
@bblimke All tests green using master 🎉!
