### ISSUE TITLE
Testing SSL client certificates

### ISSUE THREAD

**Issue by nomasprime** [bblimke/webmock#757]
Hi,

I'm building a client that uses SSL client certificates, not something I've done before.

Is this possible to test with WebMock and how would I go about it?

Thanks 🙂

**Comment by bblimke** [comment]
WebMock operates in HTTP layer.  SSL is one level above.

If you want to test the certificates then you probably need to add expectations on specific http client configuration.

**Comment by nomasprime** [comment]
Ah OK, suspected that might be the case. Thanks @bblimke 👍
