### ISSUE TITLE
Reset only history (not stubs)

### ISSUE THREAD

**Issue by chiperific** [bblimke/webmock#760]
I have run into a few times where I want to only reset the `execute count` and not "un-load" the stubs.

For example: a model where API calls are made on create and update. 
To test the update calls, I first create test records (e.g. FactoryBot). But since creation also triggers the API, my execute count is inflated before my test (in this case both create and update rely on POST, so I can't filter them out).

Using this `WebMock::RequestRegistry.instance.reset!` works (with maybe no unintended consequences?), but it might be nice to have a `WebMock.reset_history!` or `WebMock.reset_count!` so it feels a bit more intentionally available.

I'd offer a PR, but I'm a hobbyist and only understand about half of what I see.

**Comment by bblimke** [comment]
@chiperific WebMock::RequestRegistry.instance.reset! is the right way to do it.

Not sure what would be the best name to add to the API. `reset_executed_requests`, `reset_request_history`?

**Comment by chiperific** [comment]
I'd vote for `WebMock.reset_executed_requests` since that relates more directly to the error message.

E.g: `expect(WebMock).to have_requested(:post, /url_regex/).twice`
Msg: `The request POST /url_regex/ was expected to execute 2 times but it executed 4 times`

Sorry I can't be helpful with a PR. I have a tendency to create two new problems for each one I solve.

**Comment by bblimke** [comment]
@chiperific You're welcome to submit a PR. No worries, I'll review it before merging :)

**Comment by chiperific** [comment]
Hey friends, I hate to say this, but this isn't working for me from RubyGems.

I've confirmed I'm on 3.4.2 (from RubyGems) and have made sure by manually `gem uninstall webmock` and reinstalling. My `Gemfile.lock` says 3.4.2, but when I run `gem open webmock`, the `api.rb` file doesn't include the new def (nor does the Readme).

If I source it in my Gemfile like this, it does work:
`gem 'webmock', git: 'https://github.com/bblimke/webmock.git', branch: 'master'`

Seems like a RubyGems issue?

**Comment by oliakremmyda** [comment]
Hi! No this is not a RubyGems issue, 3.4.2 does not include this additional API call. 
When a new release will be published you will be able to use it without getting the master branch. :)

**Comment by chiperific** [comment]
So I'm reading this backward?
https://github.com/bblimke/webmock/compare/v3.4.2...master

**Comment by oliakremmyda** [comment]
Yes this is exactly what it means :) 
If you notice [here](https://github.com/bblimke/webmock/releases/tag/v3.4.2) it says ` 4 commits to master since this tag`.
When the new version is published you will see the last commit to be something like this one https://github.com/bblimke/webmock/commit/b6c5b43644b209a45b3d71e17b230dcc1fc5d056 and will be visible [here](https://github.com/bblimke/webmock/releases).
