### ISSUE TITLE
Blocking real SFTP connections in test environment

### ISSUE THREAD

**Issue by itmart** [bblimke/webmock#801]
Hi,

We are using Minitest to test our code and we usually stub out the SFTP request so it won't hit the real SFTP server, using the [`Net::SFTP gem`](https://github.com/net-ssh/net-sftp). I was just wondering if there's a way to make WebMock's `disable_net_connect!` to also block SFTP connection? From my own testing, it doesn't seem like 

```WebMock.disable_net_connect!(allow_localhost: true)``` 

blocks SFTP connections.

Thanks!

**Comment by bblimke** [comment]
@itmart Net::SFTP is for FTP over SSH. WebMock is for stubbing and setting expectations of HTTP requests, not SSH requests.
I'd suggest creating a few helper methods that internally stub Net::SFTP and take advantage of these in your tests.

**Comment by itmart** [comment]
Thanks @bblimke, I was hoping WebMock would have some settings to block SFTP requests but thank you for your suggestion!
