### ISSUE TITLE
Stubbing regexps does not seem to work / request for easier way to stub subdomains

### ISSUE THREAD

**Issue by unikitty37** [bblimke/webmock#807]
I am trying to stub all requests to a domain, and all its subdomains. However, regexp stubbing does not appear to be working for me:

```ruby
stub_request(:any, /example.com/).with(body: 'IT WORKS')
result = Net::HTTP.get(URI('http://a.example.com/'))
expect(result).to eq('IT WORKS')
```

gives the following result

```
 WebMock::NetConnectNotAllowedError:
   Real HTTP connections are disabled. Unregistered request: GET http://a.example.com/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'a.example.com', 'User-Agent'=>'Ruby'}

   You can stub this request with the following snippet:

   stub_request(:get, "http://a.example.com/").
     with(
       headers: {
   	  'Accept'=>'*/*',
   	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
   	  'Host'=>'a.example.com',
   	  'User-Agent'=>'Ruby'
       }).
     to_return(status: 200, body: "", headers: {})

   registered request stubs:

   stub_request(:any, "/example.com/").
     with(
       body: "IT WORKS")
```

This seems to be contrary to what the README says. It's a bit worrying that the regexp appears to have been converted to a literal string in the registered request stub, rather than remaining a regexp.

I'm running WebMock 3.4.2, but I can't see anything in the CHANGELOG that would have fixed this between 3.4.2 and 3.5.1…

(Would that regexp of `/example.com/` also match `example.com.au`? It's not clear from the README whether you should end the regexp with `\z` or just match a slash to prevent that happening. Either way, would it be possible to have an `and_subdomains: true` parameter to `stub_request` that would remove the need to mess about with regexps for this?)

**Comment by bblimke** [comment]
any chance you wanted to use `.to_return(body: 'IT WORKS')` instead of `.with(body: 'IT WORKS')`?

**Comment by unikitty37** [comment]
🤦‍♂️ Ah, that makes a lot more sense. Sorry for the issue spam.

What is the correct way to anchor the URL to stop `/example.com/` also matching `example.com.au`, though? It's a corner case, but I'm sure somebody will hit it eventually…

**Comment by bblimke** [comment]
how about `/example.com\//`
