### ISSUE TITLE
`hashdiff` Uses Non-Standard Constant

### ISSUE THREAD

**Issue by jfelchner** [bblimke/webmock#822]
Due to this issue: https://github.com/liufengyun/hashdiff/issues/45 `hashdiff` will be removing its current constant in the 1.0 release.  Due to webmock's popularity I thought it prudent to let you all know considering your gemspec does not currently have a pessimistic lock on that gem.

The upgrade path is extremely simple.  A find and replace in the project from `HashDiff` to `Hashdiff` will work exactly the same as before.  No require path changes are necessary.

Once `hashdiff` cuts `0.4.0`, I'd suggest cutting a webmock version with those constants renamed, and putting a `'>= 0.4.0'` on `hashdiff` in the gemspec.  Then, when we cut the `1.0`, the only change in webmock should be changing the version in the gemspec to `~> 1.0`.

**Comment by jfelchner** [comment]
@bblimke I went ahead and created a PR for you. ;)

I'll let you know as soon as `hashdiff` `0.4.0` is released.

**Comment by McRip** [comment]
`0.4.0` has been releasend. see https://rubygems.org/gems/hashdiff/versions/0.4.0.

**Comment by jfelchner** [comment]
@McRip see the PR for more info: https://github.com/bblimke/webmock/pull/823#issuecomment-496723279

**Comment by bblimke** [comment]
@jfelchner WebMock 3.6.0 has been released. Thank you for the heads-up before releasing hashdiff 0.4.0 and for PR. I very much appreciate that :)

**Comment by jfelchner** [comment]
@bblimke no problem. :)  Just another heads up that, depending on the complaining about the warning, we'll be releasing `hashdiff` `1.0` which removes the shim at some point soon.  The `3.6.0` version of `webmock` should auto-upgrade to that and the warning your users are experiencing should simply go away.

**Comment by teeparham** [comment]
I'm still seeing the warning with webmock 3.6.0 + hashdiff 0.4.0:

```
$ gem list hashdiff

*** LOCAL GEMS ***
hashdiff (0.4.0)

$ gem list webmock

*** LOCAL GEMS ***
webmock (3.6.0)

$ irb
> require "webmock"
The HashDiff constant used by this gem conflicts with another gem of a similar name.  As of version 1.0 the HashDiff constant will be completely removed and replaced by Hashdiff.  For more information see https://github.com/liufengyun/hashdiff/issues/45
```

**Comment by bblimke** [comment]
@jfelchner when do you plan to release 1.0?

**Comment by jfelchner** [comment]
@teeparham You're supposed to see the warning with `0.4.0`.  If you wish to remove the warning, you'll need to force yourself onto the `1.0` beta version.  You can follow the instructions [here](https://github.com/liufengyun/hashdiff/issues/45#issuecomment-499566400)

**Comment by bblimke** [comment]
@jfelchner when do you expect to release the version 1.0?

**Comment by jfelchner** [comment]
@bblimke I'll do that today.

**Comment by jfelchner** [comment]
@bblimke https://github.com/liufengyun/hashdiff/pull/74

**Comment by bblimke** [comment]
@jfelchner thank you. I actually meant pushing the version to rubygems.com :)

**Comment by jfelchner** [comment]
@bblimke yeah I know but that's up to @liufengyun.  I don't have access to push new versions of that gem.

**Comment by bblimke** [comment]
ah ok, thank you 👍

**Comment by jfelchner** [comment]
@bblimke released :)

**Comment by bblimke** [comment]
Excellent. Thank you!
