### ISSUE TITLE
Mock doesn't work if it matches `:80` or `:443`

### ISSUE THREAD

**Issue by thisismydesign** [bblimke/webmock#827]
```
require 'webmock'
require 'net/http'

include WebMock::API
WebMock.enable!

stub_request(:get, %r{example.com/user:1}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:1')
# => '{}'

stub_request(:get, "http://example.com/user:443").to_return(body: "{}")
Net::HTTP.get('http://example.com', '/user:443')
# => WebMock::NetConnectNotAllowedError

stub_request(:get, %r{example.com/user:443}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:443')
# => WebMock::NetConnectNotAllowedError

stub_request(:get, %r{example.com/user:443/likes}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:443/likes')
# => WebMock::NetConnectNotAllowedError

stub_request(:get, %r{example.com/user:80}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:80')
# => WebMock::NetConnectNotAllowedError

stub_request(:get, %r{example.com/user:801}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:801')
# => WebMock::NetConnectNotAllowedError

stub_request(:get, %r{example.com/user:4435}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:4435')
# => WebMock::NetConnectNotAllowedError
```

The error itself is also very misleading since you can see the correct stub registered (i.e. it doesn't print the correct URL which is being stubbed):
```
WebMock::NetConnectNotAllowedError (Real HTTP connections are disabled. Unregistered request: GET http://https//example.com:80/user:80 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'})

You can stub this request with the following snippet:

stub_request(:get, "http://https//example.com:80/user:80").
  with(
    headers: {
          'Accept'=>'*/*',
          'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
          'User-Agent'=>'Ruby'
    }).
  to_return(status: 200, body: "", headers: {})

registered request stubs:

stub_request(:get, "/example.com\/user:80/")
```

My guess is that this line is responsible:
https://github.com/bblimke/webmock/blob/d8686502442d9830dcccd24a1120ac08413d857a/lib/webmock/util/uri.rb#L84

**Comment by thisismydesign** [comment]
On second look, this doesn't work either:
```
stub_request(:get, %r{example.com/user.443}).to_return(body: "{}")
Net::HTTP.get('https://example.com', '/user:443')
# => WebMock::NetConnectNotAllowedError
```

So something like "Mock doesn't work if it matches `:80` or `:443`"

**Comment by bblimke** [comment]
@thisismydesign you are using `Net::HTTP.get` incorrectly. Please check the docs: https://ruby-doc.org/stdlib-2.6.3/libdoc/net/http/rdoc/Net/HTTP.html#method-c-get
Either
`Net::HTTP.get('https://example.com/user:443')` or `Net::HTTP.get('example.com', '/user:443')`, but not `Net::HTTP.get('https://example.com', '/user:443')`

**Comment by thisismydesign** [comment]
@bblimke Interesting, thanks. We discovered this issue when using https://github.com/GetStream/stream-ruby, this is just a way I managed to reproduce it (they actually use faraday). It could be that there's another underlying issue, but the requests work fine and the mocks don't. I can forward this issue to them if you think this cannot happen because of webmock.

**Comment by bblimke** [comment]
@thisismydesign I don't think it's worth addressing an issue related to incorrect invocation of `Net::HTTP.get`, though if there is a valid scenario when invoking `Net::HTTP` correctly, then this is something that needs to be fixed in WebMock. I'd just like to add a valid spec to WebMock with valid `Net::HTTP` invocation.

**Comment by fcheung** [comment]
I found that

```
require 'webmock'
require 'net/http'

include WebMock::API
WebMock.enable!

stub_request(:get, %r{example.com/user1}).to_return(body: "user=1")
Net::HTTP.get_response('example.com', '/user:801')
```

passes, when I would have expected it to raise WebMock::NetConnectNotAllowedError/. The code in `webmock/lib/webmock/util/uri.rb` highlighted by @thisismydesign is replacing `:80` no matter where it occurs in the uri. My reading of rfc 3986 is that `:` is allowed in the path ( https://tools.ietf.org/html/rfc3986#appendix-A )

Changing it to %r{(:80)|(:443)(/|^)} would be marginally more robust but is something more sophisticated to remove default port required?

**Comment by bblimke** [comment]
@fcheung thank you. Yes, I agree a more robust solution is required.

**Comment by thisismydesign** [comment]
Tested my use case with `v3.8.0`, it's resolved.

Thanks for the fix @fcheung!
