### ISSUE TITLE
RequestPattern does not match domain without TLD / period since v 3.4.2

### ISSUE THREAD

**Issue by eikes** [bblimke/webmock#828]
A Addressable::Template without a period in the domain will not be matched:

    template = Addressable::Template.new('localhost:3000/api/user{?identifier}')
    WebMock::API.stub_request(:get, template).to_return 'something'

I have narrowed the error down to the changes introduced in webmock version 3.4.2, before that it worked. I assume this is the commit: 2bf4453f6a26bd9300c17e611cf54d24eb65a956

**Comment by bblimke** [comment]
Thank you for reporting that @eikes . Since you have narrowed it down to the commit, do you know how to fix it? Would you fancy submitting a PR with the fix?

**Comment by eikes** [comment]
The culprit seems to be the addition of ```WebMock::Util::URI.heuristic_parse```, which delegates to ```[Addressable::URI.heuristic_parse](https://github.com/sporkmonger/addressable/blob/60e119e12624475870e23af1b79905b037ebc48f/lib/addressable/uri.rb#L164)``` which adds the http schema to the template only when the template contains a period (last case of the when statement). The ```WebMock::Util::URI.variations_of_uri_as_strings``` is called to find the match within matches_with_variations method, which DOES add the ```http``` schema to the variations, so the match is not made. So either we add the plain string without the schema to the matches_with_variations method or change the heuristic_parse method in the addressable gem.

**Comment by eikes** [comment]
OK, I was able to fix my problem. See the associated PR.

**Comment by bblimke** [comment]
@eikes excellent 👍 Thank you!
