### ISSUE TITLE
undefined method `write_timeout=' for StubSocket

### ISSUE THREAD

**Issue by robjlucas** [bblimke/webmock#862]
Getting this after upgrading to Ruby 2.6.5:

```
undefined method `write_timeout=' for #<StubSocket:0x00007fc8ed04a728 @read_timeout=80>
/Users/misteruser/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:773:in `write_timeout='
```

Ruby 2.6 added `write_timeout` and `write_timeout=` to `Net::HTTP` and `Net::BufferedIO`.

See the discussion here: https://bugs.ruby-lang.org/issues/13396

**Comment by bblimke** [comment]
Have you upgraded webmock to latest version as well?

**Comment by robjlucas** [comment]
> Have you upgraded webmock to latest version as well?

Yep, this is on webmock 3.7.6
