### ISSUE TITLE
Unable to return integer header values

### ISSUE THREAD

**Issue by jonmerrill2012** [bblimke/webmock#872]
On webmock 3.7.6, but I think its been this way for ~10 years. Also using HTTPParty 0.13.7

https://github.com/bblimke/webmock/blob/master/lib/webmock/util/headers.rb#L16
If I understand correctly, header values are always being cast to strings, this is problematic when header values can be integers.

Repro:
```
      WebMock.stub_request(:get, "foo.com")
        .to_return(
          status: 200,
          body: "",
          headers: { "X-Integer-Value" => 100 }
        )
```

The response payload will be similar to this:
```
payload.headers
  > {"x-integer-value"=>["100"]}

payload.headers["x-integer-value"]
  > "100"
```

Would it be possible to support integer header values? I see in your examples you show off setting `"Content-Length => 3`, which will also be returned as a string.

**Comment by bblimke** [comment]
@jonmerrill2012 as far as I'm aware HTTP header values need to be treated as strings. I can consider changing it if you can point me to http spec or some rfc which says that header values can be numeric.

**Comment by jonmerrill2012** [comment]
We should be good to close this, HTTParty must be doing some coercing or Im somehow receiving an integer header.

I wasnt able to find anything indicating a numeric value was supported, and it appears strings are expected. https://tools.ietf.org/html/rfc7230#section-3.2.4

Thank you for looking into it.
