### ISSUE TITLE
Older HTTP.rb Versions Broken with 3.8.1

### ISSUE THREAD

**Issue by drcapulet** [bblimke/webmock#875]
#874 passes through the body encoding to HTTP.rb, but uses keyword arguments which weren't used until v3. Based on [this version check](https://github.com/bblimke/webmock/blob/v3.8.1/lib/webmock/http_lib_adapters/http_rb_adapter.rb#L8), 0.6.0+ should be supported.

I can either submit a PR to bump that version to `3.0.0`, or use position or keyword arguments based on the gem's version, which would you prefer?

This is how the error manifests:

```
TypeError:
  no implicit conversion of Hash into String
# http-2.2.2/lib/http/response/body.rb:47:in `find'
# http-2.2.2/lib/http/response/body.rb:47:in `to_s'
# http-2.2.2/lib/http/response.rb:91:in `flush'
```

**Comment by bblimke** [comment]
@drcapulet thanks for reporting this. I think it's still worth supporting versions < 3 as well.
