### ISSUE TITLE
Testing that http client to external API timeouts

### ISSUE THREAD

**Issue by kanevk** [bblimke/webmock#911]
I need to test that my HTTP client to external API timeouts in exactly XX seconds.

## Context
 - Webmock version - 3.9
 - Sinatra based REST JSON API
 - On an API call I make a call to Github's API
 - I use Rspec + Webmock
 - I use the [httprb/http](https://github.com/httprb/http) library for the remote requests

The SUT is my GithubClient. I want to assert the call `GithubClient#fetch_libraries(timeout_at: [Time])` times out at the specified time **when the request takes longer**.

The `fetch_libraries` implementation:
```
def fetch_libraries(timeout_at:)
  response = HTTP.timeout(timeout_at - Time.now.utc).get("....").to_s
  ...
  return [...] # libraries
end
```

## Question

How to make the following work?

```ruby
it 'timeouts due to HTTP timeout when the request takes too long' do
  stub_request(:get, /github\.com/).to_return(:body => lambda { |request| sleep 0.2; '[]' })

  expect do
    client.fetch_libraries(timeout_at: Time.now.utc + 0.1)
  end.to raise_error(FetchLibraries::TimeoutError)
end

# Failure/Error:
# ...
# => expected FetchLibraries::TimeoutError but nothing was raised
```

**Comment by bblimke** [comment]
@kanevk by stubbing the request, you instruct the http client to return 200 response, only that building the body for that response will take 0.2 seconds more. 
The request will therefore return 200 response instead of timing out.

There is no way to stub the request to timeout. You can only stub the request to raise a specific timeout error.

**Comment by kanevk** [comment]
@bblimke fair point.

What about the `to_rack` syntax. I expect it to work for my use-case?
```ruby
stub_request(:get, /github\.com/).to_rack(lambda { |env| sleep 0.2; [200, {}, '[]'] })`
```

Do you think that my approach is wrong or it's just too hard to test it and it doesn't worth it?

**Comment by bblimke** [comment]
Timeout errors are usually raised on socket or connection levels, by passing various parameters.

It's hard for WebMock to mock that as WebMock would need to have own implementation,
to replace that behaviour on the http client library level. In reality that would only test
the implementation faked by WebMock and not provide any guarantee that the timeouts
would work against real sockets and connections.

**Comment by kanevk** [comment]
@bblimke, that makes sense. I'm closing the issue, thanks!
