### ISSUE TITLE
Overwriting Test::Unit's teardown causes WebMock to not reset

### ISSUE THREAD

**Issue by jessebs** [bblimke/webmock#915]
The standard way of having 'end-of-test' logic is to overwrite the teardown method in the test class. 

Doing so, however, removes the alias that webmock/test_unit creates, causing WebMock.reset! to not be called.

Calling super in the teardown method avoids this behavior, but that is a non-standard approach and also isn't documented in WebMock (that I could find at least)

**Comment by bblimke** [comment]
@jessebs do you have any suggestion how to handle it? I don't think test unit has support for callbacks in the same way as e.g RSpec does.

**Comment by jessebs** [comment]
See PR #919
