### ISSUE TITLE
JSON::ParserError when stubbing a non-json response body

### ISSUE THREAD

**Issue by Glis** [bblimke/webmock#935]
Hi guys. We are trying to use webmock to stub a request from an external API that responds with a single `0` or `1` on the body. But when we tried to stub that, we received the following error:
```
MyClass#call_endpoint when response is zero return true
     Failure/Error: else JSON.parse(response.body)
     JSON::ParserError:
       A JSON text must at least contain two octets!
```

The code we are using to stub the request is the following:
``` ruby
before do
  stub_const('MyClass::BASE_URL', 'http://test.external-api.url')
  stub_request(:post, "http://test.external-api.url/endpoint").to_return(status: 200, body: mocked_response, headers: {})
end
context 'when response is zero' do
  let(:mocked_response) { '0' }

  it 'return true' do
    expect(described_class.call_endpoint(params)).to be_truthy
  end
end
```
Internally the service object that is being tested just verifies the response's body, and if it's `0` returns `true`, and otherwise returns `false`.

Is is actually possible with webmock to mock responses that are not objects or arrays coming from APIs? or this is still not yet supported? We may be stubbing it wrong, but we did search a lot and couldn't find an example on how to stub this kind of responses.

Thank you in advance!

**Comment by bblimke** [comment]
@Glis are you sure that the error comes from WebMock?

Can you please run rspec with `-b` option to show the full backtrace?

There is no `else JSON.parse(response.body)` in WebMock's codebase.

**Comment by Glis** [comment]
Hey! thanks for the answer. We debbuged a lil bit more with the backtrace and we figured that some code in one of the wrappers we used did that JSON.parse. so...

My bad there. Feel free to delete this issue, sorry 🤦🏾

**Comment by bblimke** [comment]
No worries, these things happen. I'm glad you managed to find the root cause.
