### ISSUE TITLE
Inspect digital certificate with HTTPClient

### ISSUE THREAD

**Issue by cesarjr** [bblimke/webmock#961]
Hi!

I'd like to ensure that the request is being done using digital certificate.

Is there a way to check `http.ssl_config.set_client_cert_file`?

```ruby
http = HTTPClient.new
http.ssl_config.set_client_cert_file(decrypted_certificate, decrypted_key)
http.post(url, [request_body].to_json, headers)
```

**Comment by bblimke** [comment]
That is HTTPClient specific, therefore if you want to test things like that, I suggest querying or setting expectations on HTTPClient, not on WebMock.

**Comment by cesarjr** [comment]
Actually I'd like to test what certificate and private key is being sent to the endpoint. Not exactly `set_client_cert_file ` option. That's why I thought about test it using webmock.

This way I would let my tests more agnostics about implementation.

I'm gonna keep mocking HTTPClient.

Thank you!
