### ISSUE TITLE
Top-Level array in JSON body

### ISSUE THREAD

**Issue by cedrics** [bblimke/webmock#983]
Hey, we are calling an external API that expects the JSON body to be an array of hashes. It was a bit confusing to us that this does not work. 

Would you be interessted in a PR that extends the `BodyPattern` to support top level arrays? So make this test pass:

```ruby
it "should match if the request body has a top level array" do
  expect(WebMock::RequestPattern.new(:post, 'www.example.com', body: [{a: 1}])).
    to match(WebMock::RequestSignature.new(:post, "www.example.com",
    headers: {content_type: content_type}, body: "[{\"a\":1}]"))
end
```

Thanks for the great work on `webmock`. Love the library ❤️

**Comment by bblimke** [comment]
Hi @cedrics .

Yes, I'd definitely be keen to make it work. I'm surprised as well that it's not supported, that nobody raised that over the last 11-12 years ;)
